'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {MemoryDb}=require('./helpers/memory-mongo');
const governance=require('../src/lib/accounting-governance');
const ledger=require('../src/lib/profit-commission-ledger');

const accounting={username:'khedmati-test',role:'accounting'};
const manager={username:'manager-test',role:'manager'};
const admin={username:'admin-test',role:'admin'};
const seller={username:'seller-test',role:'seller'};
const evidence={reason:'Verified against controlled test evidence',sourceReference:'TEST-DOC-1',evidenceMetadata:{attachmentId:'ATT-1'}};
const governedEvidence={reason:'Verified against controlled test evidence',sourceReference:'TEST-DOC-1',attachmentMetadata:{attachmentId:'ATT-1'}};

function facts(){return[
  {factId:'F1',fifoDatasetId:'FIFO-1',saleLineIdentity:'L1',saleDate:'14050410',sellerIdentity:'S1',itemGuid:'I1',itemCode:'NB-1',quantityExact:'1.000000',saleAmountExact:'950.00',actualFifoProfitExact:'200.00',costCoverageStatus:'complete',invoiceDiscountAttributionStatus:'official-line-or-zero'},
  {factId:'F2',fifoDatasetId:'FIFO-1',saleLineIdentity:'L2',saleDate:'14050411',sellerIdentity:'S1',itemGuid:'I2',itemCode:'CP-1',quantityExact:'1.000000',saleAmountExact:'50.00',actualFifoProfitExact:null,costCoverageStatus:'unknown',invoiceDiscountAttributionStatus:'unresolved-invoice-level'}
];}
function dbSeed(extra={}){return new MemoryDb({fifoProfitFacts:facts(),...extra});}

test('official Item/Get normalization preserves stable child and parent identities and duplicate group numbers',async()=>{
  const db=dbSeed();let call=0;const shaygan={getItemsPage:async()=>{call++;return call===1?{ok:true,totalRecords:2,list:[
    {raw:{ItemGuId:'I1',ItemCode:'NB-1',ItemGroupGuId:'G-A',ItemGroupNumber:'10',ItemGroupName:'Notebook',ParentItemGroupGuId:'P-A',ParentItemGroupNumber:'1',ParentItemGroupName:'Portable'}},
    {raw:{ItemGuId:'I2',ItemCode:'CP-1',ItemGroupGuId:'G-B',ItemGroupNumber:'10',ItemGroupName:'Component',ParentItemGroupGuId:'P-B',ParentItemGroupNumber:'2',ParentItemGroupName:'Parts'}}
  ]}:{ok:true,totalRecords:2,list:[]};}};const result=await governance.refreshOfficialGroupCatalog(db,shaygan,{pageSize:100},accounting);assert.equal(result.run.pagesRead,1);assert.equal(result.run.groupCount,2);assert.equal(result.run.ambiguousNumbers.length,1);assert.deepEqual(result.run.ambiguousNumbers[0].groupIdentities.sort(),['guid:G-A','guid:G-B']);assert.equal(db.collection(governance.ITEM_GROUP_ASSIGNMENTS).rows[0].source,'shaygan-official-read');assert.equal(result.inventoryWrites,0);assert.equal(result.automaticMappingsApproved,0);
});

test('missing parent hierarchy is explicit and never treated as accounting evidence',async()=>{
  const normalized=governance.normalizeOfficialItem({ItemGuId:'I1',ItemCode:'1',ItemGroupGuId:'G1',ItemGroupNumber:'10',ItemGroupName:'Notebook'});assert.equal(normalized.hierarchyStatus,'parent-unavailable-from-official-response');assert.equal(normalized.parentGroupGuid,'');const db=dbSeed({accountingOfficialItemGroupAssignments:[{...normalized,active:true}]});const report=await governance.groupReviewMatrix(db,{fifoDatasetId:'FIFO-1',periodFrom:'14050401',periodTo:'14050431'},accounting);assert.equal(report.list[0].hierarchyStatus,'parent-unavailable-from-official-response');assert.match(report.list[0].suggestionEvidence,/human evidence required|never auto-approved/i);assert.equal(report.automaticApproval,false);
});

test('category mapping workflow requires evidence, role separation, revision and overlap safety',async()=>{
  const db=dbSeed();const created=await ledger.createCategoryMapping(db,{itemGuid:'I1',commissionCategory:'NOTEBOOK',effectiveFrom:'14050401',effectiveTo:'14050431'},accounting);assert.equal(created.mapping.status,'draft');await assert.rejects(ledger.transitionCategoryMapping(db,created.mapping.mappingId,'submit',{revision:1},accounting),e=>e.code==='CATEGORY_MAPPING_EVIDENCE_REQUIRED');const submitted=await ledger.transitionCategoryMapping(db,created.mapping.mappingId,'submit',{revision:1,...evidence},accounting);await assert.rejects(ledger.transitionCategoryMapping(db,created.mapping.mappingId,'approve',{revision:2,...evidence},accounting),e=>e.code==='PROFIT_LEDGER_FORBIDDEN');await assert.rejects(ledger.transitionCategoryMapping(db,created.mapping.mappingId,'approve',{revision:99,...evidence},manager),e=>e.code==='CATEGORY_MAPPING_CONFLICT');const approved=await ledger.transitionCategoryMapping(db,created.mapping.mappingId,'approve',{revision:submitted.mapping.revision,...evidence},manager);assert.equal(approved.mapping.status,'approved');assert.equal(approved.automaticApproval,false);
  const overlap=await ledger.createCategoryMapping(db,{itemGuid:'I1',commissionCategory:'COMPONENT',effectiveFrom:'14050415',effectiveTo:'14050501',...evidence},accounting);const pending=await ledger.transitionCategoryMapping(db,overlap.mapping.mappingId,'submit',{revision:1,...evidence},accounting);await assert.rejects(ledger.transitionCategoryMapping(db,overlap.mapping.mappingId,'approve',{revision:pending.mapping.revision,...evidence},manager),e=>e.code==='CATEGORY_MAPPING_OVERLAP');
});

test('category approval is serialized per stable identity',async()=>{
  const db=dbSeed();const created=await ledger.createCategoryMapping(db,{itemGuid:'I1',commissionCategory:'NOTEBOOK',effectiveFrom:'14050401',effectiveTo:'14050431',...evidence},accounting);const submitted=await ledger.transitionCategoryMapping(db,created.mapping.mappingId,'submit',{revision:1,...evidence},accounting);db.collection(ledger.CATEGORY_APPROVAL_LOCKS).rows.push({lockKey:'itemGuid|I1',owner:'other-approver',expiresAt:new Date(Date.now()+10000)});await assert.rejects(ledger.transitionCategoryMapping(db,created.mapping.mappingId,'approve',{revision:submitted.mapping.revision,...evidence},manager),e=>e.code==='APPROVAL_LOCKED');assert.equal(db.collection(ledger.CATEGORY_MAPPINGS).rows[0].status,'pending');
});

test('rate workflow distinguishes blank from zero and supports exact seller override without hidden default',async()=>{
  const db=dbSeed();await assert.rejects(ledger.createRateVersion(db,{sellerIdentity:'*',commissionCategory:'NOTEBOOK',rate:'',effectiveFrom:'14050401',...evidence},accounting),e=>e.code==='RATE_REQUIRED');const global=await ledger.createRateVersion(db,{sellerIdentity:'*',commissionCategory:'NOTEBOOK',rate:'0.14000000',effectiveFrom:'14050401',effectiveTo:'14050431',...evidence},accounting);const gs=await ledger.transitionRateVersion(db,global.rateVersion.rateVersionId,'submit',{revision:1,...evidence},accounting);await ledger.transitionRateVersion(db,global.rateVersion.rateVersionId,'approve',{revision:gs.rateVersion.revision,...evidence},manager);const special=await ledger.createRateVersion(db,{sellerIdentity:'S1',commissionCategory:'NOTEBOOK',rate:'0.35000000',effectiveFrom:'14050401',effectiveTo:'14050431',...evidence},accounting);const ss=await ledger.transitionRateVersion(db,special.rateVersion.rateVersionId,'submit',{revision:1,...evidence},accounting);await ledger.transitionRateVersion(db,special.rateVersion.rateVersionId,'approve',{revision:ss.rateVersion.revision,...evidence},manager);const resolved=await ledger.resolveRate(db,'S1','NOTEBOOK','14050410');assert.equal(resolved.rateVersion.rate,'0.35000000');assert.equal((await ledger.resolveRate(db,'OTHER','COMPONENT','14050410')).status,'missing');
});

test('Tir rate review matrix covers seller/category scope and marks missing rates explicitly',async()=>{
  const db=dbSeed({commissionCategoryMappings:[{mappingId:'M1',identityType:'itemGuid',identityValue:'I1',commissionCategory:'NOTEBOOK',effectiveFrom:'14050401',effectiveTo:'14050431',status:'approved'}],commissionRateVersions:[{rateVersionId:'R1',sellerIdentity:'*',commissionCategory:'NOTEBOOK',rate:'0.14000000',effectiveFrom:'14050401',effectiveTo:'14050431',status:'pending',sourceReference:'TIR-WORKBOOK'}]});const report=await governance.rateReviewMatrix(db,{fifoDatasetId:'FIFO-1'},accounting);const notebook=report.list.find(row=>row.commissionCategory==='NOTEBOOK');const unknown=report.list.find(row=>row.commissionCategory==='UNKNOWN');assert.equal(notebook.proposedRate,'0.14000000');assert.equal(notebook.rateStatus,'pending');assert.equal(notebook.rateClassification,'standard-global');assert.equal(unknown.rateStatus,'missing');assert.equal(report.blankRateIsZero,false);
});

test('opening balance requires source evidence, independent approval, isolated pools and idempotent single posting',async()=>{
  const db=dbSeed();await assert.rejects(governance.createOpeningBalance(db,{pool:'COMPONENT',accountingPeriod:'140504',amountExact:'500'},accounting),e=>e.code==='OPENING_EVIDENCE_REQUIRED');const created=await governance.createOpeningBalance(db,{pool:'COMPONENT',accountingPeriod:'140504',amountExact:'500',sourceDocumentType:'Management packet',...governedEvidence},accounting);const submitted=await governance.transitionOpeningBalance(db,created.openingBalance.openingBalanceId,'submit',{revision:1},accounting);await assert.rejects(governance.transitionOpeningBalance(db,created.openingBalance.openingBalanceId,'approve',{revision:submitted.openingBalance.revision,...governedEvidence},accounting),e=>e.code==='ACCOUNTING_GOVERNANCE_FORBIDDEN');const approved=await governance.transitionOpeningBalance(db,created.openingBalance.openingBalanceId,'approve',{revision:submitted.openingBalance.revision,...governedEvidence},manager);assert.equal(approved.ledgerEntry.pool,'COMPONENT');assert.equal(approved.ledgerEntry.creditAmountExact,'500.00');const replay=await governance.transitionOpeningBalance(db,created.openingBalance.openingBalanceId,'approve',{revision:approved.openingBalance.revision,...governedEvidence},manager);assert.equal(replay.idempotent,true);assert.equal(db.collection(ledger.SAVED_LEDGER).rows.length,1);assert.equal((await ledger.savedBalance(db,'NOTEBOOK')).balanceExact,'0.00');assert.equal((await ledger.savedBalance(db,'COMPONENT')).balanceExact,'500.00');
});

test('opening reversal is a separate approval workflow and cannot silently alter the original',async()=>{
  const db=dbSeed();const original=await governance.createOpeningBalance(db,{pool:'NOTEBOOK',accountingPeriod:'140504',amountExact:'100',sourceDocumentType:'Workbook',...governedEvidence},accounting);const os=await governance.transitionOpeningBalance(db,original.openingBalance.openingBalanceId,'submit',{revision:1},accounting);const oa=await governance.transitionOpeningBalance(db,original.openingBalance.openingBalanceId,'approve',{revision:os.openingBalance.revision,...governedEvidence},manager);const reversal=await governance.createOpeningBalance(db,{pool:'NOTEBOOK',accountingPeriod:'140504',amountExact:'100',entryKind:'REVERSAL',reversalOf:oa.openingBalance.openingBalanceId,sourceDocumentType:'Reversal approval',...governedEvidence},accounting);assert.equal(reversal.openingBalance.status,'draft');assert.equal(db.collection(ledger.SAVED_LEDGER).rows.length,1);const rs=await governance.transitionOpeningBalance(db,reversal.openingBalance.openingBalanceId,'submit',{revision:1},accounting);await governance.transitionOpeningBalance(db,reversal.openingBalance.openingBalanceId,'approve',{revision:rs.openingBalance.revision,...governedEvidence},manager);assert.equal(db.collection(ledger.SAVED_LEDGER).rows.length,2);assert.equal((await ledger.savedBalance(db,'NOTEBOOK')).balanceExact,'0.00');
});

test('only one approved opening balance may exist per pool and period',async()=>{
  const db=dbSeed();async function pending(amount,source){const c=await governance.createOpeningBalance(db,{pool:'NOTEBOOK',accountingPeriod:'140504',amountExact:amount,sourceDocumentType:'Workbook',...governedEvidence,sourceReference:source},accounting);return governance.transitionOpeningBalance(db,c.openingBalance.openingBalanceId,'submit',{revision:1},accounting);}const first=await pending('100','DOC-A');await governance.transitionOpeningBalance(db,first.openingBalance.openingBalanceId,'approve',{revision:first.openingBalance.revision,...governedEvidence},manager);const second=await pending('200','DOC-B');await assert.rejects(governance.transitionOpeningBalance(db,second.openingBalance.openingBalanceId,'approve',{revision:second.openingBalance.revision,...governedEvidence},manager),e=>e.code==='OPENING_APPROVED_DUPLICATE');assert.equal(db.collection(ledger.SAVED_LEDGER).rows.length,1);
});

test('readiness exposes approved/projected coverage and normal export is blocked with machine-readable reasons',async()=>{
  const db=dbSeed({commissionCategoryMappings:[{mappingId:'M1',identityType:'itemGuid',identityValue:'I1',commissionCategory:'NOTEBOOK',effectiveFrom:'14050401',effectiveTo:'14050431',status:'approved'},{mappingId:'M2',identityType:'itemGuid',identityValue:'I2',commissionCategory:'COMPONENT',effectiveFrom:'14050401',effectiveTo:'14050431',status:'pending'}],commissionRateVersions:[{rateVersionId:'R1',sellerIdentity:'S1',commissionCategory:'NOTEBOOK',rate:'0.14',effectiveFrom:'14050401',effectiveTo:'14050431',status:'approved'}]});const result=await governance.readiness(db,{fifoDatasetId:'FIFO-1',periodFrom:'14050401',periodTo:'14050431'},accounting);assert.equal(result.metrics.mappedSaleValuePercent,95);assert.equal(result.metrics.projectedMappedSaleValuePercent,100);assert.equal(result.normalExportReady,false);assert.equal(result.blockers.some(x=>x.code==='UNMAPPED_LINES'),true);assert.equal(result.blockers.some(x=>x.code==='COST_COVERAGE_INCOMPLETE'),true);await assert.rejects(ledger.createExcelExport(db,{fifoDatasetId:'FIFO-1'},accounting),e=>e.code==='COMMISSION_EXPORT_NOT_READY'&&Array.isArray(e.blockers));
});

test('diagnostic export is explicit, admin-only, audited and never contains a payable total',async()=>{
  const db=dbSeed();await assert.rejects(ledger.createExcelExport(db,{fifoDatasetId:'FIFO-1',exportMode:'diagnostic',...governedEvidence},accounting),e=>e.code==='ACCOUNTING_GOVERNANCE_FORBIDDEN');const result=await ledger.createExcelExport(db,{fifoDatasetId:'FIFO-1',exportMode:'diagnostic',...governedEvidence},admin);assert.equal(result.exportMode,'diagnostic');assert.equal(result.payable,false);assert.match(result.content,/INCOMPLETE DIAGNOSTIC ONLY/);assert.equal(db.collection(governance.EXPORT_OVERRIDES).rows.length,1);
});

test('normal export opens only after every governed prerequisite is approved',async()=>{
  const readyFacts=facts().map(row=>row.factId==='F2'?{...row,actualFifoProfitExact:'10.00',costCoverageStatus:'complete',invoiceDiscountAttributionStatus:'official-line-or-zero'}:row);const db=new MemoryDb({fifoProfitFacts:readyFacts,commissionCategoryMappings:[{mappingId:'M1',identityType:'itemGuid',identityValue:'I1',commissionCategory:'NOTEBOOK',effectiveFrom:'14050401',effectiveTo:'14050431',status:'approved'},{mappingId:'M2',identityType:'itemGuid',identityValue:'I2',commissionCategory:'COMPONENT',effectiveFrom:'14050401',effectiveTo:'14050431',status:'approved'}],commissionRateVersions:[{rateVersionId:'R1',sellerIdentity:'S1',commissionCategory:'NOTEBOOK',rate:'0.14',effectiveFrom:'14050401',effectiveTo:'14050431',status:'approved'},{rateVersionId:'R2',sellerIdentity:'S1',commissionCategory:'COMPONENT',rate:'0.20',effectiveFrom:'14050401',effectiveTo:'14050431',status:'approved'}],savedProfitOpeningBalances:[{openingBalanceId:'O1',pool:'NOTEBOOK',accountingPeriod:'140504',entryKind:'OPENING',status:'approved'},{openingBalanceId:'O2',pool:'COMPONENT',accountingPeriod:'140504',entryKind:'OPENING',status:'approved'}]});const ready=await governance.readiness(db,{fifoDatasetId:'FIFO-1'},accounting);assert.equal(ready.normalExportReady,true);assert.equal(ready.blockers.length,0);const exported=await ledger.createExcelExport(db,{fifoDatasetId:'FIFO-1'},accounting);assert.equal(exported.exportMode,'normal');assert.equal(exported.payable,false);assert.equal(exported.content.includes('INCOMPLETE DIAGNOSTIC ONLY'),false);
});

test('seller has no access and source/UI contracts preserve accounting boundaries',async()=>{
  const db=dbSeed();await assert.rejects(governance.groupReviewMatrix(db,{},seller),e=>e.code==='ACCOUNTING_GOVERNANCE_FORBIDDEN');const source=fs.readFileSync(path.join(__dirname,'../src/lib/accounting-governance.js'),'utf8');for(const forbidden of ['Invoice/Put','PutSaleInvoice','PutBuyInvoice','saleSnapshotDatasetLines.update','fifoProfitFacts.update','supplierPurchaseLayers.update','itemInventoryCatalog.update'])assert.equal(source.includes(forbidden),false,forbidden);const ui=fs.readFileSync(path.join(__dirname,'../public/assets/app.js'),'utf8');assert.match(ui,/commission-category-governance/);assert.match(ui,/saved-profit-opening-governance/);assert.match(ui,/COMMISSION_EXPORT_NOT_READY|Normal export/);assert.match(ui,/excelDiagnostic/);assert.match(ui,/Diagnostic Export \(incomplete \/ non-payable\)/);assert.match(ui,/data-action="\$\{action\}"/);assert.match(ui,/action==='edit'\?editRecord/);const sellerPages=ui.match(/seller:\s*\[([^\]]+)\]/)?.[1]||'';assert.equal(sellerPages.includes('commission-category-governance'),false);assert.equal(sellerPages.includes('saved-profit-opening-governance'),false);
});
