'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {MemoryDb}=require('./helpers/memory-mongo');
const service=require('../src/lib/financial-source-control');

const accounting={username:'khedmati',role:'accounting'};
const admin={username:'admin',role:'admin'};
const manager={username:'manager',role:'manager'};
const seller={username:'seller01',role:'seller'};

function allocation(datasetId,saleLineId,sourceType,extra={}){return {datasetId,allocationId:`${datasetId}-${saleLineId}-${extra.allocationSequence||1}`,saleLineId,allocationSequence:extra.allocationSequence||1,saleInvoiceType:2,saleInvoiceNo:extra.saleInvoiceNo||100,saleDate:'14050410',sellerAccountNumber:extra.seller||'11701013',officialProductCategoryName:extra.category||'NOTEBOOK',itemCode:extra.itemCode||saleLineId,soldQuantity:extra.soldQuantity||'1.000000',quantityExact:extra.quantityExact||'1.000000',allocatedSaleValueExact:extra.saleValue||'100.00',allocatedCostAmountExact:sourceType==='unknown_cost'?null:(extra.cost||'60.00'),unitCostExact:extra.unitCost||'60.000000',sourceType,unknownReason:extra.unknownReason||'',purchaseLineIdentity:extra.purchaseLineIdentity||'',purchaseInvoiceNo:extra.purchaseInvoiceNo||0,purchaseInvoiceDate:extra.purchaseInvoiceDate||'',supplierAccountNumber:extra.supplier||'',supplierName:extra.supplierName||'',manualResolutionId:extra.manualResolutionId||''};}
function seed(){return new MemoryDb({
  purchaseLayerDatasetState:[{scopeKey:'purchase-invoices-types-3-7',activeDatasetId:'P-A'}],
  purchaseLayerDatasets:[
    {datasetId:'P-A',status:'completed',activationStatus:'active',sourceDateFrom:'14040101',sourceDateTo:'14050431',purchaseInvoiceCount:1,purchaseLineCount:1,sourceFingerprint:'PA',layerFingerprint:'PAL',validation:{valid:true},completedAt:new Date('2026-08-01')},
    {datasetId:'P-C',status:'completed',activationStatus:'validated-candidate',sourceDateFrom:'14030101',sourceDateTo:'14050431',purchaseInvoiceCount:2,purchaseLineCount:2,sourceFingerprint:'PC',layerFingerprint:'PCL',validation:{valid:true,duplicateIdentityCount:0},completedAt:new Date('2026-08-02')}
  ],
  supplierPurchaseLayers:[
    {datasetId:'P-A',purchaseLineIdentity:'L-1',purchaseInvoiceNo:1200,purchaseInvoiceDate:'14050301',supplierAccountNumber:'S-1',supplierName:'Supplier 1',itemCode:'I1',itemGuid:'G1',itemDescription:'Item 1',netPurchasedQuantity:1,netUnitCost:50,layerKind:'purchase',sourceHash:'H1'},
    {datasetId:'P-C',purchaseLineIdentity:'L-1',purchaseInvoiceNo:1200,purchaseInvoiceDate:'14050301',supplierAccountNumber:'S-1',supplierName:'Supplier 1',itemCode:'I1',itemGuid:'G1',itemDescription:'Item 1',netPurchasedQuantity:1,netUnitCost:50,layerKind:'purchase',sourceHash:'H1'},
    {datasetId:'P-C',purchaseLineIdentity:'L-2',purchaseInvoiceNo:1231,purchaseInvoiceDate:'14050315',supplierAccountNumber:'S-2',supplierName:'Supplier 2',itemCode:'12D3209250',itemGuid:'G2',itemDescription:'Recovered item',netPurchasedQuantity:2,netUnitCost:70,layerKind:'purchase',sourceHash:'H2'}
  ],
  fifoDatasetState:[{scopeKey:'fifo-shadow-v2-precision-evidence',activeDatasetId:'F-A'}],
  fifoDatasets:[
    {datasetId:'F-A',status:'completed',activationStatus:'validated-shadow',sourceSaleSnapshotId:'SALE-A',sourcePurchaseDatasetId:'P-A',sourceFingerprint:'FA',allocationFingerprint:'FAA',validation:{valid:true},completedAt:new Date('2026-08-01')},
    {datasetId:'F-C',status:'completed',activationStatus:'candidate',sourceSaleSnapshotId:'SALE-A',sourcePurchaseDatasetId:'P-C',sourceFingerprint:'FC',allocationFingerprint:'FCA',manualResolutionSetFingerprint:'MSET',validation:{valid:true},completedAt:new Date('2026-08-03')}
  ],
  fifoAllocations:[
    allocation('F-A','SL1','official_purchase_layer',{itemCode:'I1',purchaseLineIdentity:'L-1',purchaseInvoiceNo:1200}),
    allocation('F-A','SL4','unknown_cost',{itemCode:'I4',saleInvoiceNo:104,saleValue:'80.00',unknownReason:'NO_PURCHASE_HISTORY'}),
    allocation('F-C','SL1','official_purchase_layer',{itemCode:'I1',purchaseLineIdentity:'L-1',purchaseInvoiceNo:1200}),
    allocation('F-C','SL2','official_purchase_layer',{itemCode:'I2',saleInvoiceNo:102,soldQuantity:'2.000000',quantityExact:'1.000000',saleValue:'100.00',cost:'50.00',allocationSequence:1,purchaseLineIdentity:'L-A'}),
    allocation('F-C','SL2','official_purchase_layer',{itemCode:'I2',saleInvoiceNo:102,soldQuantity:'2.000000',quantityExact:'1.000000',saleValue:'100.00',cost:'60.00',allocationSequence:2,purchaseLineIdentity:'L-B'}),
    allocation('F-C','SL3','approved_manual_cost',{itemCode:'I3',saleInvoiceNo:103,manualResolutionId:'MC-1',cost:'45.00'}),
    allocation('F-C','SL4','unknown_cost',{itemCode:'I4',saleInvoiceNo:104,saleValue:'80.00',unknownReason:'NO_PURCHASE_HISTORY'})
  ],
  fifoExceptions:[],
  manualCostResolutions:[{resolutionId:'MC-1',status:'approved',revision:2,deleted:false,itemCode:'I3',manualCostExact:'45.000000',resolutionScope:'item',effectiveFrom:'14050101',effectiveTo:'',contentHash:'a'.repeat(64),createdBy:accounting,approvedBy:admin,auditLog:[{action:'approved'}]}],
  purchaseLayerRecoveryCandidates:[{candidateId:'REC-1',itemCode:'I4',purchaseInvoiceNo:999}],
  financialSourceReviews:[],financialSourceReviewActions:[],openingInventoryEvidence:[]
});}

test('active and candidate Purchase datasets are selected dynamically',async()=>{const out=await service.overview(seed(),{},accounting);assert.equal(out.purchase.active.datasetId,'P-A');assert.equal(out.purchase.candidate.datasetId,'P-C');});
test('overview never makes activation available',async()=>{const out=await service.overview(seed(),{},admin);assert.equal(out.activationAvailable,false);});
test('Purchase candidate delta preserves prior valid layer',async()=>{const out=await service.purchaseDelta(seed(),{},accounting);assert.equal(out.summary.previousLayerPreservationPass,true);});
test('new purchase invoice and line are displayed',async()=>{const out=await service.purchaseDelta(seed(),{invoiceNumber:'1231'},accounting);assert.equal(out.total,1);assert.equal(out.list[0].changeTypes[0],'NEW_LINE');});
test('supplier trace is preserved in purchase delta',async()=>{const out=await service.purchaseDelta(seed(),{supplier:'Supplier 2'},accounting);assert.equal(out.list[0].supplierIdentity,'S-2');});
test('item trace and source fingerprint are preserved',async()=>{const out=await service.purchaseDelta(seed(),{item:'12D3209250'},accounting);assert.equal(out.list[0].sourceFingerprint,'H2');});
test('Purchase delta exposes duplicate identity validation',async()=>{const db=seed();db.collection('supplierPurchaseLayers').rows.push(structuredClone(db.collection('supplierPurchaseLayers').rows.at(-1)));const out=await service.purchaseDelta(db,{},accounting);assert.equal(out.summary.duplicateIdentities,1);});
test('Purchase filters and server pagination are bounded',async()=>{const out=await service.purchaseDelta(seed(),{page:1,pageSize:1},accounting);assert.equal(out.pageSize,1);assert.equal(out.list.length,1);assert.ok(out.total>=2);});
test('all required source gap buckets are stable contract values',()=>{assert.deepEqual(service.GAP_BUCKETS,['NO_PURCHASE_HISTORY','PURCHASE_MISSING_FROM_DATASET','NEGATIVE_CHRONOLOGY','OPENING_INVENTORY_CANDIDATE','PURCHASE_RETURN_CONFLICT','MANUAL_COST_REQUIRED','MANUAL_COST_INELIGIBLE','IDENTITY_MISMATCH','UNSUPPORTED']);});
test('recovered purchase evidence classifies dataset gap',async()=>{const out=await service.sourceGaps(seed(),{},accounting);assert.equal(out.list[0].bucket,'PURCHASE_MISSING_FROM_DATASET');});
test('gap financial exposure is aggregated',async()=>{const out=await service.sourceGaps(seed(),{},accounting);const row=out.summary.find(value=>value.bucket==='PURCHASE_MISSING_FROM_DATASET');assert.equal(row.saleValue,80);assert.equal(row.lineCount,1);});
test('gap classifier separates chronology and return conflict',()=>{assert.equal(service._gapBucket({unknownReason:'negative chronology'},{}),'NEGATIVE_CHRONOLOGY');assert.equal(service._gapBucket({}, {returnConflict:true}),'PURCHASE_RETURN_CONFLICT');});
test('cost evidence unifies manual and opening evidence types',async()=>{const db=seed();db.collection(service.OPENING).rows.push({evidenceId:'O1',status:'pending',itemCode:'I5',openingDate:'14050101',unitCostExact:'20',quantityExact:'1'});const out=await service.costEvidence(db,{},accounting);assert.deepEqual(new Set(out.list.map(row=>row.evidenceType)),new Set(['MANUAL_COST_ITEM_LEGACY','OPENING_INVENTORY_EVIDENCE']));});
test('legacy manual-cost warning is explicit and Persian',async()=>{const out=await service.costEvidence(seed(),{},accounting);assert.match(out.list[0].legacyWarning,/فاکتور خرید مشخص/);});
test('manual-cost supersession fields remain visible',async()=>{const db=seed();db.collection('manualCostResolutions').rows[0].supersedesResolutionId='MC-OLD';const out=await service.costEvidence(db,{},accounting);assert.equal(out.list[0].supersedes,'MC-OLD');});
test('Opening Evidence draft requires item date quantity cost and source',async()=>{await assert.rejects(service.createOpeningDraft(seed(),{},accounting),error=>error.code==='JALALI_DATE_INVALID'||error.code==='OPENING_EVIDENCE_ITEM_REQUIRED');});
test('Opening Evidence draft stores immutable audit metadata',async()=>{const out=await service.createOpeningDraft(seed(),{itemCode:'I5',openingDate:'14050101',quantity:'2',unitCost:'30',sourceType:'physical_count',sourceReference:'DOC-1',description:'opening count'},accounting);assert.equal(out.evidence.status,'draft');assert.equal(out.evidence.auditLog[0].by.username,'khedmati');assert.equal(out.evidence.immutableAfterApproval,true);});
test('Opening Evidence uses optimistic revision control',async()=>{const db=seed();const created=await service.createOpeningDraft(db,{itemCode:'I5',openingDate:'14050101',quantity:'2',unitCost:'30',sourceType:'physical_count',sourceReference:'DOC-1',description:'opening count'},accounting);await assert.rejects(service.updateOpeningDraft(db,created.evidence.evidenceId,{revision:9,description:'changed'},accounting),error=>error.code==='OPENING_EVIDENCE_REVISION_CONFLICT');});
test('Opening Evidence creator cannot independently approve',async()=>{const db=seed();const created=await service.createOpeningDraft(db,{itemCode:'I5',openingDate:'14050101',quantity:'2',unitCost:'30',sourceType:'physical_count',sourceReference:'DOC-1',description:'opening count'},admin);await service.transitionOpening(db,created.evidence.evidenceId,'submit',{revision:1},admin);await assert.rejects(service.transitionOpening(db,created.evidence.evidenceId,'approve',{revision:2},admin),error=>error.code==='OPENING_EVIDENCE_SELF_APPROVAL');});
test('Opening Evidence supports independent approval without FIFO writes',async()=>{const db=seed();const before=structuredClone(db.collection('fifoDatasets').rows);const created=await service.createOpeningDraft(db,{itemCode:'I5',openingDate:'14050101',quantity:'2',unitCost:'30',sourceType:'physical_count',sourceReference:'DOC-1',description:'opening count'},accounting);await service.transitionOpening(db,created.evidence.evidenceId,'submit',{revision:1},accounting);const approved=await service.transitionOpening(db,created.evidence.evidenceId,'approve',{revision:2},admin);assert.equal(approved.evidence.status,'approved');assert.deepEqual(db.collection('fifoDatasets').rows,before);});
test('FIFO provenance reports official single-layer source',async()=>{const out=await service.fifoLines(seed(),{item:'I1'},accounting);assert.equal(out.list[0].costSourceType,'OFFICIAL_PURCHASE_LAYER');});
test('FIFO provenance reports multi-purchase-layer source',async()=>{const out=await service.fifoLines(seed(),{item:'I2'},accounting);assert.equal(out.list[0].costSourceType,'MULTI_PURCHASE_LAYER');});
test('FIFO provenance reports governed legacy manual source',async()=>{const out=await service.fifoLines(seed(),{item:'I3'},accounting);assert.equal(out.list[0].costSourceType,'MANUAL_COST_ITEM_LEGACY');assert.equal(out.list[0].provenanceSources[0].manualCostResolutionId,'MC-1');});
test('unknown cost has no fake FIFO profit',async()=>{const out=await service.fifoLines(seed(),{item:'I4'},accounting);assert.equal(out.list[0].profitProvenanceStatus,'UNKNOWN');assert.equal(out.list[0].fifoProfitExact,null);});
test('aggregate labels proven FIFO profit as non-total profit',async()=>{const out=await service.fifoSummary(seed(),{},accounting);assert.equal(out.labels.notTotalProfit,true);assert.match(out.labels.profit,/اثبات‌شده/);});
test('FIFO summary reports newly proven and regression counts',async()=>{const out=await service.fifoSummary(seed(),{},accounting);assert.equal(out.delta.newlyProven,2);assert.equal(out.delta.regressions,0);});
test('candidate review follows accounting then independent admin workflow',async()=>{const db=seed();let out=await service.candidateReview(db,'purchase-dataset','P-C','start-review',{},accounting);assert.equal(out.review.state,'HUMAN_REVIEW');out=await service.candidateReview(db,'purchase-dataset','P-C','accounting-approve',{revision:1},accounting);assert.equal(out.review.state,'ACCOUNTING_APPROVED');out=await service.candidateReview(db,'purchase-dataset','P-C','admin-approve',{revision:2},admin);assert.equal(out.review.state,'ADMIN_APPROVED');assert.equal(out.activationPerformed,false);});
test('candidate creator or accounting reviewer cannot self-approve final gate',async()=>{const db=seed();await service.candidateReview(db,'purchase-dataset','P-C','start-review',{},admin);await service.candidateReview(db,'purchase-dataset','P-C','accounting-approve',{revision:1},admin);await assert.rejects(service.candidateReview(db,'purchase-dataset','P-C','admin-approve',{revision:2},admin),error=>error.code==='SOURCE_REVIEW_SELF_APPROVAL');});
test('line review is append-only audit evidence',async()=>{const db=seed();const out=await service.lineReview(db,{entityType:'purchase-dataset',entityId:'P-C',lineIdentity:'L-2',action:'mismatch',note:'quantity differs',sourceFingerprint:'H2'},accounting);assert.equal(out.action.immutable,true);assert.equal(db.collection(service.ACTIONS).rows.length,1);});
test('activation preview has no activation endpoint or effect',async()=>{const db=seed();const before=structuredClone(db.collection('fifoDatasetState').rows);const out=await service.activationPreview(db,'fifo-dataset','F-C',admin);assert.equal(out.activationEndpointAvailable,false);assert.equal(out.activationPerformed,false);assert.deepEqual(db.collection('fifoDatasetState').rows,before);});
test('GET services cause zero writes',async()=>{const db=seed();const before=JSON.stringify([...db.collections].map(([name,collection])=>[name,collection.rows]));await service.overview(db,{},accounting);await service.purchaseDelta(db,{},accounting);await service.sourceGaps(db,{},accounting);await service.costEvidence(db,{},accounting);await service.fifoLines(db,{},accounting);await service.fifoSummary(db,{},accounting);await service.reviewCenter(db,{},accounting);const after=JSON.stringify([...db.collections].map(([name,collection])=>[name,collection.rows]));assert.equal(after,before);});
test('seller role is denied by service contract',async()=>{await assert.rejects(service.overview(seed(),{},seller),error=>error.code==='FINANCIAL_SOURCE_CONTROL_FORBIDDEN'&&error.statusCode===403);});
test('core UI uses one route and one menu label',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/assets/financial-source-control.js'),'utf8');assert.match(source,/PAGE='financial-source-control'/);assert.equal((source.match(/button\.textContent='کنترل منابع مالی'/g)||[]).length,1);});
test('core UI is Persian-first with four required tabs',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/assets/financial-source-control.js'),'utf8');for(const label of ['منابع خرید','نواقص و کسری مأخذ','شواهد هزینه','FIFO و مأخذ سود'])assert.match(source,new RegExp(label));});
test('module has no request-time Shaygan or invoice mutation call',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/lib/financial-source-control.js'),'utf8');for(const forbidden of ['require(\'./shaygan\')','Invoice/Put','putInvoice','supplierPurchaseLayers.update','fifoDatasetState.update'])assert.equal(source.includes(forbidden),false,forbidden);});
test('server publishes preview but no activation route',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/server.js'),'utf8');assert.ok(source.includes('financial-source-control\\/activation-preview'));assert.doesNotMatch(source,/financial-source-control\\\/activate(?:\\\/|')/);});
test('historical audit arrays survive evidence projection unchanged',async()=>{const out=await service.costEvidence(seed(),{},accounting);assert.deepEqual(out.list[0].auditLog,[{action:'approved'}]);});
