'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {MemoryDb}=require('./helpers/memory-mongo');
const manual=require('../src/lib/manual-cost-resolution');
const fsc=require('../src/lib/financial-source-control');

const accounting={username:'khedmati',role:'accounting'};
const admin={username:'admin',role:'admin'};
function db(){return new MemoryDb({
  purchaseLayerDatasetState:[{scopeKey:'purchase-invoices-types-3-7',activeDatasetId:'P-A'}],
  purchaseLayerDatasets:[{datasetId:'P-A',status:'completed',activationStatus:'active',completedAt:new Date('2026-08-10')},{datasetId:'P-C',status:'completed',activationStatus:'candidate',completedAt:new Date('2026-08-11')}],
  supplierPurchaseLayers:[
    {datasetId:'P-C',purchaseLineIdentity:'L1',layerKind:'purchase',validationStatus:'valid',itemGuid:'G-X',itemCode:'X',purchaseInvoiceNo:10,purchaseInvoiceDate:'14050101',supplierAccountNumber:'S1',supplierName:'A',netPurchasedQuantityExact:'2',netUnitCostExact:'100',sourceHash:'h1'},
    {datasetId:'P-C',purchaseLineIdentity:'L2',layerKind:'purchase',validationStatus:'valid',itemGuid:'G-X',itemCode:'X',purchaseInvoiceNo:11,purchaseInvoiceDate:'14050102',supplierAccountNumber:'S2',supplierName:'B',netPurchasedQuantityExact:'3',netUnitCostExact:'200',sourceHash:'h2'},
    {datasetId:'P-C',purchaseLineIdentity:'FUT',layerKind:'purchase',validationStatus:'valid',itemGuid:'G-X',itemCode:'X',purchaseInvoiceNo:12,purchaseInvoiceDate:'14050201',netPurchasedQuantityExact:'100',netUnitCostExact:'999',sourceHash:'hf'},
    {datasetId:'P-C',purchaseLineIdentity:'BAD',layerKind:'purchase',validationStatus:'rejected',itemGuid:'G-X',itemCode:'X',purchaseInvoiceNo:13,purchaseInvoiceDate:'14050103',netPurchasedQuantityExact:'5',netUnitCostExact:'1',sourceHash:'hb'}
  ],
  fifoDatasetState:[{scopeKey:'fifo-shadow-v2-precision-evidence',activeDatasetId:'F-A'}],
  fifoDatasets:[{datasetId:'F-A',status:'completed',activationStatus:'active',completedAt:new Date('2026-08-10')},{datasetId:'F-C',status:'completed',activationStatus:'candidate',sourcePurchaseDatasetId:'P-C',completedAt:new Date('2026-08-11')}],
  fifoAllocations:[
    {datasetId:'F-C',allocationId:'U1',sourceType:'unknown_cost',saleLineId:'SL1',saleInvoiceNo:1,saleInvoiceType:2,saleDate:'14050110',itemGuid:'G-X',itemCode:'X',itemDescription:'Item X',quantityExact:'1',allocatedSaleValueExact:'1000',sellerIdentity:'117',sellerAccountNumber:'117',sellerName:'فروشنده یک',officialProductCategoryGuid:'CPU-G',officialProductCategoryName:'CPU'},
    {datasetId:'F-C',allocationId:'U2',sourceType:'unknown_cost',saleLineId:'SL2',saleInvoiceNo:2,saleInvoiceType:2,saleDate:'14050111',itemGuid:'G-X',itemCode:'X',itemDescription:'Item X',quantityExact:'2',allocatedSaleValueExact:'3000',sellerIdentity:'118',sellerAccountNumber:'118',sellerName:'فروشنده دو',officialProductCategoryGuid:'CPU-G',officialProductCategoryName:'CPU'},
    {datasetId:'F-C',allocationId:'U3',sourceType:'unknown_cost',saleLineId:'SL3',saleInvoiceNo:3,saleInvoiceType:2,saleDate:'14050112',itemGuid:'G-Y',itemCode:'Y',itemDescription:'Item Y',quantityExact:'1',allocatedSaleValueExact:'500',sellerIdentity:'117',sellerName:'فروشنده یک',officialProductCategoryGuid:'NB-G',officialProductCategoryName:'NOTEBOOK'}
  ],
  fifoExceptions:[],manualCostResolutions:[],fifoSourceInvalidations:[],openingInventoryEvidence:[],financialSourceReviews:[],financialSourceReviewActions:[],
  accountingOfficialGroupCatalogRuns:[{catalogRunId:'CAT',fetchedAt:new Date()}],
  accountingOfficialItemGroups:[{catalogRunId:'CAT',isMainGroup:true,sourceGroupGuid:'CPU-G',groupNumber:'84',groupName:'CPU',resolvedMainGroupGuid:'CPU-G',resolvedMainGroupName:'CPU'},{catalogRunId:'CAT',isMainGroup:true,sourceGroupGuid:'NB-G',groupNumber:'1',groupName:'NOTEBOOK',resolvedMainGroupGuid:'NB-G',resolvedMainGroupName:'NOTEBOOK'}]
});}

test('weighted average suggestion uses authoritative quantity basis',()=>{const result=manual._suggestionFromLayers(db().collection('supplierPurchaseLayers').rows.filter(x=>x.datasetId==='P-C'),{itemGuid:'G-X',itemCode:'X'},'14050110');assert.equal(result.suggestedCostExact,'160.000000');assert.equal(result.quantityBasisExact,'5.000000');});
test('suggestion excludes future purchases',()=>{const result=manual._suggestionFromLayers(db().collection('supplierPurchaseLayers').rows,{itemGuid:'G-X'},'14050110');assert.deepEqual(result.sourcePurchaseIds,['10','11']);});
test('suggestion excludes invalid purchases',()=>{const result=manual._suggestionFromLayers(db().collection('supplierPurchaseLayers').rows,{itemGuid:'G-X'},'14050110');assert.equal(result.purchaseCount,2);});
test('suggestion exposes min max latest and fingerprint',()=>{const result=manual._suggestionFromLayers(db().collection('supplierPurchaseLayers').rows,{itemGuid:'G-X'},'14050110');assert.equal(result.minPurchaseCostExact,'100.000000');assert.equal(result.maxPurchaseCostExact,'200.000000');assert.equal(result.latestPurchaseCostExact,'200.000000');assert.match(result.sourceFingerprint,/^[a-f0-9]{64}$/);});
test('no historical purchase means no suggestion and never zero cost',()=>{const result=manual._suggestionFromLayers([],{itemCode:'NONE'},'14050110');assert.equal(result.available,false);assert.equal(result.suggestedCostExact,null);});
test('suggestion API is read-only',async()=>{const store=db(),before=structuredClone(store.collection('manualCostResolutions').rows);const result=await manual.assistedSuggestion(store,{purchaseDatasetId:'P-C',itemGuid:'G-X',applicableDate:'14050110'},accounting);assert.equal(result.suggestedCostExact,'160.000000');assert.deepEqual(store.collection('manualCostResolutions').rows,before);});
test('Accounting can accept suggestion without Admin',async()=>{const store=db();const result=await manual.assistedDecision(store,{decision:'APPROVE_SUGGESTED',purchaseDatasetId:'P-C',itemGuid:'G-X',itemCode:'X',applicableDate:'14050110',effectiveFrom:'14050101'},accounting);assert.equal(result.resolution.status,'approved');assert.equal(result.resolution.approvedBy.username,'khedmati');assert.equal(result.adminApprovalRequired,false);});
test('Admin can finalize assisted evidence without a second approval',async()=>{const result=await manual.assistedDecision(db(),{decision:'APPROVE_SUGGESTED',purchaseDatasetId:'P-C',itemGuid:'G-X',applicableDate:'14050110',effectiveFrom:'14050101'},admin);assert.equal(result.resolution.approvedBy.username,'admin');assert.equal(result.adminApprovalRequired,false);});
test('override requires reason',async()=>{await assert.rejects(manual.assistedDecision(db(),{decision:'APPROVE_OVERRIDE',purchaseDatasetId:'P-C',itemGuid:'G-X',applicableDate:'14050110',effectiveFrom:'14050101',finalCost:'170'},accounting),error=>error.code==='MANUAL_COST_DECISION_REASON_REQUIRED');});
test('override records exact delta',async()=>{const result=await manual.assistedDecision(db(),{decision:'APPROVE_OVERRIDE',purchaseDatasetId:'P-C',itemGuid:'G-X',applicableDate:'14050110',effectiveFrom:'14050101',finalCost:'170',reason:'سند حسابداری'},accounting);assert.equal(result.resolution.deltaAmountExact,'10.000000');assert.equal(result.resolution.decisionType,'overridden');});
test('manual entry without suggestion requires reason',async()=>{await assert.rejects(manual.assistedDecision(db(),{decision:'APPROVE_OVERRIDE',purchaseDatasetId:'P-C',itemGuid:'G-Z',itemCode:'Z',applicableDate:'14050110',effectiveFrom:'14050101',finalCost:'50'},accounting),error=>error.code==='MANUAL_COST_DECISION_REASON_REQUIRED');});
test('manual entry with reason remains distinct from official layer',async()=>{const result=await manual.assistedDecision(db(),{decision:'APPROVE_OVERRIDE',purchaseDatasetId:'P-C',itemGuid:'G-Z',itemCode:'Z',applicableDate:'14050110',effectiveFrom:'14050101',finalCost:'50',reason:'سند قدیمی'},accounting);assert.equal(result.resolution.decisionType,'manual-entry');assert.equal(result.resolution.sourceType,'manual');});
test('assisted audit records all lifecycle states',async()=>{const result=await manual.assistedDecision(db(),{decision:'APPROVE_SUGGESTED',purchaseDatasetId:'P-C',itemGuid:'G-X',applicableDate:'14050110',effectiveFrom:'14050101'},accounting);assert.deepEqual(result.resolution.auditLog.map(x=>x.action),['assisted-needs-review','assisted-accounting-review','assisted-approved']);});
test('approval marks future FIFO source stale without mutating historical FIFO',async()=>{const store=db(),before=structuredClone(store.collection('fifoAllocations').rows);await manual.assistedDecision(store,{decision:'APPROVE_SUGGESTED',purchaseDatasetId:'P-C',itemGuid:'G-X',applicableDate:'14050110',effectiveFrom:'14050101'},accounting);assert.equal(store.collection('fifoSourceInvalidations').rows.length,1);assert.deepEqual(store.collection('fifoAllocations').rows,before);});
test('queue aggregates sale lines by authoritative unresolved target',async()=>{const result=await fsc.manualCostQueue(db(),{fifoDatasetId:'F-C'},accounting);const x=result.list.find(row=>row.itemGuid==='G-X');assert.equal(x.affectedSaleLines,2);assert.equal(x.saleValueExposure,4000);});
test('queue sorts exposure descending',async()=>{const result=await fsc.manualCostQueue(db(),{fifoDatasetId:'F-C'},accounting);assert.equal(result.list[0].itemGuid,'G-X');});
test('bulk safety keys differ across unrelated targets',async()=>{const result=await fsc.manualCostQueue(db(),{fifoDatasetId:'F-C'},accounting);assert.notEqual(result.list[0].bulkKey,result.list[1].bulkKey);assert.equal(result.bulkSafety,'same-bulkKey-only');});
test('selector list uses canonical seller stable identities',async()=>{const result=await fsc.selectorOptions(db(),{fifoDatasetId:'F-C'},accounting);assert.deepEqual(result.sellers.map(x=>x.sellerIdentity).sort(),['117','118']);assert.equal(result.sources.sellers,'canonical-fifo-consumer-read-model');});
test('category selector uses official Shaygan catalog GUID',async()=>{const result=await fsc.selectorOptions(db(),{fifoDatasetId:'F-C'},accounting);assert.deepEqual(result.categories.map(x=>x.officialProductCategoryGuid),['CPU-G','NB-G']);assert.equal(result.sources.categories,'official-shaygan-product-category-catalog');});
test('FIFO seller query uses exact stable seller identity',async()=>{const result=await fsc.fifoLines(db(),{fifoDatasetId:'F-C',sellerIdentity:'118'},accounting);assert.equal(result.total,1);assert.equal(result.list[0].sellerIdentity,'118');});
test('FIFO category query uses exact official category GUID',async()=>{const result=await fsc.fifoLines(db(),{fifoDatasetId:'F-C',categoryGuid:'NB-G'},accounting);assert.equal(result.total,1);assert.equal(result.list[0].officialProductCategoryGuid,'NB-G');});
test('opening inventory governance is unchanged',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/lib/financial-source-control.js'),'utf8');assert.match(source,/OPENING_STATES/);assert.match(source,/transitionOpening/);assert.match(source,/APPROVE_ROLES/);});
test('runtime Seller Performance does not invoke legacy FIFO calculator',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/lib/sale-snapshot.js'),'utf8');const runtime=source.slice(source.indexOf('async function sellerPerformance'),source.indexOf('module.exports'));assert.doesNotMatch(runtime,/computeSellerProfitFifo\s*\(/);assert.match(runtime,/profitStatus:'unavailable'/);});
test('Supplier Sleep new snapshot path keeps legacy profit disabled',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/lib/purchase-sleep.js'),'utf8');assert.match(source,/profit-paused-sale-snapshot-required/);assert.match(source,/profitStatus:'PAUSED_SALE_SNAPSHOT_PHASE'/);});
test('assisted suggestion has no Shaygan request-time dependency',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/lib/manual-cost-resolution.js'),'utf8');const body=source.slice(source.indexOf('async function assistedSuggestion'),source.indexOf('async function assistedDecision'));assert.doesNotMatch(body,/shaygan|Invoice\/Get|GetKardex/i);assert.match(body,/purchaseLayerDataset\.LAYERS/);});
test('FSC GET services do not ensure or create indexes',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/lib/manual-cost-resolution.js'),'utf8');const suggestion=source.slice(source.indexOf('async function assistedSuggestion'),source.indexOf('async function assistedDecision'));const list=source.slice(source.indexOf('async function list'),source.indexOf('function validAt'));assert.doesNotMatch(suggestion,/ensureIndexes/);assert.doesNotMatch(list,/ensureIndexes/);});
test('Persian-first FSC UI keeps Manual Cost reporting read-only',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/assets/financial-source-control.js'),'utf8');assert.match(source,/همه فروشندگان/);assert.match(source,/همه دسته‌بندی‌ها/);assert.match(source,/خرید رسمی خارج از Dataset فعلی/);assert.match(source,/گزارش هزینه دستی/);assert.doesNotMatch(source,/fscCostAccept|fscCostOverride/);});
test('Admin decision report is immutable visibility only',async()=>{const store=db();await manual.assistedDecision(store,{decision:'APPROVE_SUGGESTED',purchaseDatasetId:'P-C',itemGuid:'G-X',applicableDate:'14050110',effectiveFrom:'14050101'},accounting);const report=await fsc.manualCostDecisions(store,{},admin);assert.equal(report.adminVisibilityOnly,true);assert.equal(report.list.length,1);assert.deepEqual(report.list[0].auditLog.map(row=>row.action),['assisted-needs-review','assisted-accounting-review','assisted-approved']);});
test('canonical Purchase Engine assures bounded ItemGuid suggestion index',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/lib/purchase-layer-dataset.js'),'utf8');assert.match(source,/datasetId:1, itemGuid:1, purchaseInvoiceDate:1/);});
