'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {MemoryDb}=require('./helpers/memory-mongo');
const opening=require('../src/lib/opening-accounting-cost-basis');
const manual=require('../src/lib/manual-cost-resolution');
const shaygan=require('../src/lib/shaygan');
const fifo=require('../src/lib/fifo-shadow-engine');

const actors={admin:{username:'admin',role:'admin'},accounting:{username:'khedmati',role:'accounting'},purchase:{username:'buyer',role:'purchase'},seller:{username:'seller',role:'seller'},manager:{username:'manager',role:'manager'}};
function seed(){return new MemoryDb({
  purchaseLayerDatasetState:[{scopeKey:'purchase-invoices-types-3-7',activeDatasetId:'P1'}],
  purchaseLayerDatasets:[{datasetId:'P1',status:'completed',activationStatus:'active'}],
  supplierPurchaseLayers:[
    {datasetId:'P1',datasetSchemaVersion:1,purchaseLineIdentity:'EXACT',layerKind:'purchase',validationStatus:'valid',itemGuid:'G-E',itemCode:'E',purchaseInvoiceDate:'14050101',purchaseInvoiceNo:1,netPurchasedQuantityExact:'2',netUnitCostExact:'100',sourceHash:'a'},
    {datasetId:'P1',datasetSchemaVersion:1,purchaseLineIdentity:'H1',layerKind:'purchase',validationStatus:'valid',itemGuid:'G-H',itemCode:'H',purchaseInvoiceDate:'14040101',purchaseInvoiceNo:2,netPurchasedQuantityExact:'2',netUnitCostExact:'100',sourceHash:'b'},
    {datasetId:'P1',datasetSchemaVersion:1,purchaseLineIdentity:'H2',layerKind:'purchase',validationStatus:'valid',itemGuid:'G-H',itemCode:'H',purchaseInvoiceDate:'14040201',purchaseInvoiceNo:3,netPurchasedQuantityExact:'3',netUnitCostExact:'200',sourceHash:'c'},
    {datasetId:'P1',datasetSchemaVersion:1,purchaseLineIdentity:'HF',layerKind:'purchase',validationStatus:'valid',itemGuid:'G-H',itemCode:'H',purchaseInvoiceDate:'14060101',purchaseInvoiceNo:4,netPurchasedQuantityExact:'9',netUnitCostExact:'999',sourceHash:'d'},
    {datasetId:'P1',datasetSchemaVersion:1,purchaseLineIdentity:'HR',layerKind:'purchase',validationStatus:'valid',returnMatchStatus:'unmatched',itemGuid:'G-H',itemCode:'H',purchaseInvoiceDate:'14040301',purchaseInvoiceNo:5,netPurchasedQuantityExact:'1',netUnitCostExact:'1',sourceHash:'e'}
  ],
  openingAccountingCostBasis:[{evidenceId:'O1',status:'available',extractionComplete:true,itemGuid:'G-O',itemCode:'O',effectiveOpeningDate:'14050101',openingQuantityExact:'10.000000',openingUnitCostExact:'631958905.254546',openingTotalValueExact:'6319589052.55',sourceFields:{quantity:'BeginDurationRemainQuan1',totalValue:'BeginDurationRemainPrice1'},sourceFingerprint:'f'.repeat(64),evidenceQuality:'PROVEN_SOURCE_SUMMARY_AND_FIRST_MOVEMENT'}],
  itemCatalogAll:[...['E','H','O','N'].map(code=>({itemCode:code,itemGuid:`G-${code}`,canonicalIdentity:`guid:g${code.toLowerCase()}`,historyCompleteness:'complete'}))],
  purchaseHistoryDiscoveryQueue:[],
  openingInventoryEvidence:[],manualCostResolutions:[],fifoSourceInvalidations:[]
});}
function suggestion(db,target,actor=actors.accounting){return manual.assistedSuggestion(db,{purchaseDatasetId:'P1',applicableDate:'14050501',...target},actor);}

test('raw Kardex opening summary uses only official BeginDuration fields',()=>{const out=shaygan._normalizeKardexOpeningBasis({BeginDurationRemainQuan1:10,BeginDurationRemainPrice1:6319589052.54546});assert.equal(out.openingQuantity,10);assert.equal(out.openingTotalValue,6319589052.54546);assert.ok(Math.abs(out.openingUnitCost-631958905.254546)<0.000001);assert.deepEqual(out.sourceFields,{quantity:'BeginDurationRemainQuan1',totalValue:'BeginDurationRemainPrice1'});});
test('zero opening summary is not fabricated',()=>{assert.equal(shaygan._normalizeKardexOpeningBasis({BeginDurationRemainQuan1:0,BeginDurationRemainPrice1:1}),null);});
test('opening Kardex query sends canonical Jalali date range through the supported Domain',async()=>{const prior=global.fetch,calls=[];global.fetch=async(_url,request)=>{calls.push(JSON.parse(request.body));return{ok:true,status:200,json:async()=>({Result:calls.length===1?[{ItemCode:'O',ItemGuId:'G-O',ItemKardex:[{BeginDurationRemainQuan1:1,BeginDurationRemainPrice1:100,Date:'14050102',InvoiceNumber:1,OutComeQuan1:1}]}]:[]})};};try{const result=await shaygan.getKardexByItemCode('O','01',{dateFrom:'۱۴۰۵/۰۱/۰۱',dateTo:'1405-01-31',maxRows:3,hardMaxRows:3,timeoutMs:1000});assert.equal(result.ok,true);assert.deepEqual(calls[0].Domain.InvDate,{From:'14050101',To:'14050131',In:[]});assert.deepEqual(calls[0].Domain.STNumber,{From:'01',To:'01',In:[]});assert.equal(result.meta.openingDate,'14050101');}finally{global.fetch=prior;}});
test('materialized opening basis preserves quantity unit cost total and provenance',()=>{const row=opening.fromKardex({ok:true,item:{itemGuid:'G-O',itemCode:'O',itemDescription:'Opening'},openingBasis:{openingQuantity:10,openingTotalValue:6319589052.54546,sourceFields:{quantity:'BeginDurationRemainQuan1',totalValue:'BeginDurationRemainPrice1'}},rows:[{date:'2026-03-26',invoiceType:2,invoiceNumber:74,inQty:0,outQty:1,remainQty:9,costPrice:631958905.254545}],meta:{reachedLimit:false}},new Date('2026-08-17T00:00:00Z'));assert.equal(row.effectiveOpeningDate,'14050106');assert.equal(row.openingQuantityExact,'10.000000');assert.equal(row.openingUnitCostExact,'631958905.254546');assert.equal(row.openingTotalValueExact,'6319589052.55');assert.match(row.sourceFingerprint,/^[a-f0-9]{64}$/);});
test('global opening aggregation sums distinct applicable warehouses and values',()=>{const result=opening.aggregateWarehouseKardex([{warehouseNumber:'01',result:{ok:true,item:{itemGuid:'G-O',itemCode:'O'},openingBasis:{openingQuantity:7,openingTotalValue:700,openingUnitCost:100,sourceFields:{}},rows:[{date:'2026-03-26',outQty:1}],meta:{reachedLimit:false,stockNumber:'01'}}},{warehouseNumber:'02',result:{ok:true,item:{itemGuid:'G-O',itemCode:'O'},openingBasis:{openingQuantity:5,openingTotalValue:500,openingUnitCost:100,sourceFields:{}},rows:[{date:'2026-03-26',outQty:1}],meta:{reachedLimit:false,stockNumber:'02'}}}]);assert.equal(result.openingQuantityExact,'12.000000');assert.equal(result.openingTotalValueExact,'1200.00');assert.equal(result.openingUnitCostExact,'100.000000');assert.equal(result.warehouseCount,2);assert.equal(result.evidenceScope,'global-active-warehouses');});
test('duplicate warehouse rows are counted once',()=>{const row={ok:true,item:{itemCode:'O'},openingBasis:{openingQuantity:7,openingTotalValue:700,openingUnitCost:100,sourceFields:{}},rows:[{date:'2026-03-26',outQty:1}],meta:{reachedLimit:false,stockNumber:'01'}};const result=opening.aggregateWarehouseKardex([{warehouseNumber:'01',result:row},{warehouseNumber:'01',result:row}]);assert.equal(result.openingQuantityExact,'7.000000');assert.equal(result.duplicateWarehouseCount,1);});
test('different warehouse accounting costs preserve detail and use global value-weighted cost',()=>{const make=(stock,qty,cost)=>({warehouseNumber:stock,result:{ok:true,item:{itemCode:'O'},openingBasis:{openingQuantity:qty,openingTotalValue:qty*cost,openingUnitCost:cost,sourceFields:{}},rows:[{date:'2026-03-26',outQty:1}],meta:{reachedLimit:false,stockNumber:stock}}});const result=opening.aggregateWarehouseKardex([make('01',1,100),make('02',3,110)]);assert.equal(result.openingQuantityExact,'4.000000');assert.equal(result.openingTotalValueExact,'430.00');assert.equal(result.openingUnitCostExact,'107.500000');assert.equal(result.warehouseUnitCostVariation,true);assert.deepEqual(result.warehouseRoundedUnitCosts,['100','110']);assert.equal(result.extractionComplete,true);});
test('all-zero warehouse responses are explicit complete no-opening evidence',()=>{const result=opening.aggregateWarehouseKardex(['01','02'].map(stock=>({warehouseNumber:stock,result:{ok:true,openingBasis:null,rows:[],meta:{reachedLimit:false,stockNumber:stock,openingDate:'14050101'}}})));assert.equal(result.status,'NO_OPENING_STOCK');assert.equal(result.queriedWarehouseCount,2);assert.equal(result.openingQuantityExact,'0.000000');assert.equal(result.extractionComplete,true);});
test('authoritative zero-opening warehouses remain visible without adding quantity',()=>{const result=opening.aggregateWarehouseKardex([{warehouseNumber:'01',result:{ok:true,item:{itemCode:'O'},openingBasis:{openingQuantity:2,openingTotalValue:200,openingUnitCost:100,sourceFields:{}},rows:[{date:'2026-03-26'}],meta:{reachedLimit:false,stockNumber:'01',openingDate:'14050101'}}},{warehouseNumber:'02',result:{ok:true,item:{itemCode:'O'},openingBasis:null,rows:[],meta:{reachedLimit:false,stockNumber:'02',openingDate:'14050101'}}}]);assert.equal(result.openingQuantityExact,'2.000000');assert.equal(result.warehouseCount,1);assert.equal(result.queriedWarehouseCount,2);assert.equal(result.excludedWarehouseCount,1);assert.equal(result.warehouseEvidence[1].evidenceQuality,'AUTHORITATIVE_ZERO_OPENING_RESPONSE');assert.equal(result.warehouseEvidence[1].exclusionReason,'no-positive-authoritative-opening-basis');});
test('one failed or truncated warehouse blocks global opening materialization',()=>{const good={warehouseNumber:'01',result:{ok:true,item:{itemCode:'O'},openingBasis:{openingQuantity:2,openingTotalValue:200},rows:[{date:'2026-03-26'}],meta:{reachedLimit:false,openingDate:'14050101'}}};for(const failed of [{warehouseNumber:'02',result:{ok:false,error:'timeout',meta:{reachedLimit:false}}},{warehouseNumber:'02',result:{ok:true,openingBasis:{openingQuantity:1,openingTotalValue:100},rows:[],meta:{reachedLimit:true}}}]){const result=opening.aggregateWarehouseKardex([good,failed]);assert.equal(result.code,'OPENING_WAREHOUSE_EXTRACTION_INCOMPLETE');assert.equal(result.failedWarehouse,'02');assert.equal(result.extractionComplete,false);}});
test('real Shaygan ISO local datetime is normalized before Jalali conversion',()=>{const row=opening.fromKardex({ok:true,item:{itemCode:'O'},openingBasis:{openingQuantity:10,openingTotalValue:1000,sourceFields:{}},rows:[{date:'2026-03-26T00:00:00',outQty:1,remainQty:9}],meta:{reachedLimit:false}});assert.equal(row.effectiveOpeningDate,'14050106');});
test('truncated Kardex cannot become opening evidence',()=>{assert.equal(opening.fromKardex({ok:true,openingBasis:{openingQuantity:1,openingTotalValue:1},rows:[{date:'2026-01-01'}],meta:{reachedLimit:true}}),null);});
test('opening materialization refuses an unproven warehouse scope',async()=>{const db=new MemoryDb({settings:[],openingAccountingCostBasis:[]});const result=await opening.materialize(db,{itemCode:'O',openingDate:'14050101'},{shaygan:{getKardexByItemCode:async()=>{throw new Error('must not call unrestricted source');}}});assert.equal(result.code,'OPENING_WAREHOUSE_SCOPE_UNPROVEN');assert.equal(db.collection('openingAccountingCostBasis').rows.length,0);});
test('opening materialization reads every governed warehouse and stores one global aggregate',async()=>{const db=new MemoryDb({settings:[{key:'inventory.activeWarehouseNumbers',value:['01','02']}],openingAccountingCostBasis:[]});const calls=[];const result=await opening.materialize(db,{itemCode:'O',openingDate:'14050101'},{shaygan:{getKardexByItemCode:async(_code,stock,opts)=>{calls.push([stock,opts.dateFrom]);const qty=stock==='01'?7:5;return{ok:true,item:{itemGuid:'G-O',itemCode:'O'},openingBasis:{openingQuantity:qty,openingTotalValue:qty*100,openingUnitCost:100,sourceFields:{}},rows:[{date:'2026-03-26',outQty:1}],meta:{reachedLimit:false,stockNumber:stock}};}}});assert.deepEqual(calls,[['01','14050101'],['02','14050101']]);assert.equal(result.openingQuantityExact,'12.000000');assert.equal(db.collection('openingAccountingCostBasis').rows[0].warehouseEvidence.length,2);});
test('governed opening candidate is immutable, validated but unapproved, and writes no financial engine',async()=>{const db=new MemoryDb({settings:[{key:'inventory.activeWarehouseNumbers',value:['01','02']}],openingAccountingCostBasis:[],openingAccountingEvidenceDatasets:[],openingAccountingEvidenceState:[],supplierPurchaseLayers:[],fifoAllocations:[],manualCostResolutions:[]});const result=await opening.buildCandidate(db,{openingDate:'14050101',createdBy:actors.accounting,items:[{itemGuid:'G-O',itemCode:'O',saleQuantity:'12',saleAmount:900}]},{concurrency:2,shaygan:{getKardexByItemCode:async(_code,stock)=>({ok:true,item:{itemGuid:'G-O',itemCode:'O'},openingBasis:{openingQuantity:stock==='01'?7:5,openingTotalValue:(stock==='01'?7:5)*100,openingUnitCost:100,sourceFields:{}},rows:[{date:'2026-03-26'}],meta:{reachedLimit:false,stockNumber:stock}})}});assert.equal(result.status,'completed');assert.equal(result.approvalStatus,'validated');assert.equal(result.active,false);assert.equal(result.statusCounts.VALIDATED_CANDIDATE,1);const row=db.collection('openingAccountingCostBasis').rows[0];assert.equal(row.status,'VALIDATED_CANDIDATE');assert.equal(row.openingQuantityExact,'12.000000');assert.equal(row.immutable,true);assert.equal(db.collection('supplierPurchaseLayers').rows.length,0);assert.equal(db.collection('fifoAllocations').rows.length,0);assert.equal(db.collection('manualCostResolutions').rows.length,0);});
test('temporary Kardex failure is classified, audited and retried without duplicate evidence',async()=>{const db=new MemoryDb({settings:[{key:'inventory.activeWarehouseNumbers',value:['01']} ]});let calls=0;const result=await opening.buildCandidate(db,{openingDate:'14050110',createdBy:actors.accounting,items:[{itemGuid:'G-R',itemCode:'R'}]},{backoffMs:0,maxAttempts:3,shaygan:{getKardexByItemCode:async()=>{calls++;if(calls===1)throw new Error('request timeout');return{ok:true,item:{itemGuid:'G-R',itemCode:'R'},openingBasis:{openingQuantity:1,openingTotalValue:100,openingUnitCost:100,sourceFields:{}},rows:[{date:'2026-03-30'}],meta:{reachedLimit:false}};}}});assert.equal(result.status,'completed');const progress=db.collection(opening.PROGRESS).rows[0];assert.equal(progress.warehouseStates[0].attemptCount,2);assert.equal(progress.warehouseStates[0].attempts[0].failureClass,'TRANSIENT_TIMEOUT');assert.equal(progress.warehouseStates[0].status,'SUCCESS_POSITIVE');assert.equal(db.collection(opening.COLLECTION).rows.length,1);});
test('incomplete extraction resumes only unfinished warehouse work in the same dataset',async()=>{const db=new MemoryDb({settings:[{key:'inventory.activeWarehouseNumbers',value:['01','02']} ]});let fail=true;const api={getKardexByItemCode:async(_code,stock)=>stock==='02'&&fail?{ok:false,error:'HTTP 503',meta:{}}:{ok:true,item:{itemGuid:'G-R',itemCode:'R'},openingBasis:stock==='01'?{openingQuantity:1,openingTotalValue:100,sourceFields:{}}:null,rows:stock==='01'?[{date:'2026-03-30'}]:[],meta:{reachedLimit:false}}};const first=await opening.buildCandidate(db,{openingDate:'14050110',createdBy:actors.accounting,items:[{itemGuid:'G-R',itemCode:'R'}]},{backoffMs:0,maxAttempts:1,shaygan:api});assert.equal(first.status,'incomplete');assert.equal(db.collection(opening.COLLECTION).rows.length,0);fail=false;const resumed=await opening.resumeCandidate(db,first.datasetId,{},actors.accounting,{backoffMs:0,maxAttempts:1,shaygan:api});assert.equal(resumed.status,'completed');const progress=db.collection(opening.PROGRESS).rows[0];assert.equal(progress.warehouseStates.find(row=>row.warehouseNumber==='01').attemptCount,1);assert.equal(progress.warehouseStates.find(row=>row.warehouseNumber==='02').attemptCount,2);assert.equal(db.collection(opening.COLLECTION).rows.length,1);});
test('opening approval is independent, revisioned and forbids self approval',async()=>{const db=new MemoryDb({settings:[{key:'inventory.activeWarehouseNumbers',value:['01']} ]});const built=await opening.buildCandidate(db,{openingDate:'14050110',createdBy:actors.accounting,items:[{itemGuid:'G-A',itemCode:'A'}]},{shaygan:{getKardexByItemCode:async()=>({ok:true,item:{itemGuid:'G-A',itemCode:'A'},openingBasis:{openingQuantity:1,openingTotalValue:100,sourceFields:{}},rows:[{date:'2026-03-30'}],meta:{reachedLimit:false}})}});const submitted=await opening.submitCandidate(db,built.datasetId,{revision:1},actors.accounting);assert.equal(submitted.approvalStatus,'pending');await assert.rejects(opening.approveCandidate(db,built.datasetId,{revision:2,reason:'x'},actors.accounting),error=>error.code==='OPENING_APPROVAL_SELF_APPROVAL_FORBIDDEN');const approved=await opening.approveCandidate(db,built.datasetId,{revision:2,reason:'مدارک تطبیق شد'},actors.admin);assert.equal(approved.approvalStatus,'approved');assert.equal(db.collection(opening.APPROVALS).rows.length,2);assert.equal(db.collection(opening.COLLECTION).rows[0].approvalStatus,'draft');});
test('sale-line preview consumes opening capacity chronologically and preserves official Purchase precedence',async()=>{const db=new MemoryDb({settings:[{key:'inventory.activeWarehouseNumbers',value:['01']}],fifoDatasetState:[{scopeKey:'sale-fifo',activeDatasetId:'F1'}],fifoDatasets:[{datasetId:'F1',status:'completed'}],fifoAllocations:[{datasetId:'F1',saleLineId:'L0',saleInvoiceNo:1,saleRow:1,saleDate:'14050101',itemGuid:'G-M',itemCode:'M',sourceType:'unknown_cost',quantityExact:'1'},{datasetId:'F1',saleLineId:'L1',saleInvoiceNo:2,saleRow:1,saleDate:'14050111',itemGuid:'G-M',itemCode:'M',sourceType:'unknown_cost',quantityExact:'3'},{datasetId:'F1',saleLineId:'L2',saleInvoiceNo:3,saleRow:1,saleDate:'14050112',itemGuid:'G-M',itemCode:'M',sourceType:'unknown_cost',quantityExact:'2'},{datasetId:'F1',saleLineId:'L3',saleInvoiceNo:4,saleRow:1,saleDate:'14050113',itemGuid:'G-M',itemCode:'M',sourceType:'official_purchase_layer',quantityExact:'1'}]});const result=await opening.buildCandidate(db,{openingDate:'14050110',createdBy:actors.accounting,items:[{itemGuid:'G-M',itemCode:'M'}]},{shaygan:{getKardexByItemCode:async()=>({ok:true,item:{itemGuid:'G-M',itemCode:'M'},openingBasis:{openingQuantity:4,openingTotalValue:400,sourceFields:{}},rows:[{date:'2026-03-30'}],meta:{reachedLimit:false}})}});assert.equal(result.eligibilityPreview.rowCount,3);const rows=db.collection(opening.ELIGIBILITY).rows;assert.deepEqual(rows.map(row=>[row.saleLineIdentity,row.classification,row.openingEligibleQuantityExact]),[['L0','PRE_OPENING_PERIOD','0.000000'],['L1','OPENING_ELIGIBLE','3.000000'],['L2','OPENING_PARTIAL','1.000000']]);assert.equal(rows.some(row=>row.saleLineIdentity==='L3'),false);});
test('exact official target is classified first and Manual Cost is not required',async()=>{const out=await suggestion(seed(),{itemGuid:'G-E',itemCode:'E',purchaseLineIdentity:'EXACT'});assert.equal(out.sourceClass,'EXACT_OFFICIAL_PURCHASE_LAYER');assert.equal(out.manualCostRequired,false);});
test('opening basis outranks historical average',async()=>{const db=seed();db.collection('supplierPurchaseLayers').rows.push({datasetId:'P1',datasetSchemaVersion:1,purchaseLineIdentity:'OH',layerKind:'purchase',validationStatus:'valid',itemGuid:'G-O',itemCode:'O',purchaseInvoiceDate:'14040101',netPurchasedQuantityExact:'1',netUnitCostExact:'1'});const out=await suggestion(db,{itemGuid:'G-O',itemCode:'O',affectedQuantityExact:'3'});assert.equal(out.sourceClass,'OPENING_ACCOUNTING_COST');assert.equal(out.suggestedCostExact,'631958905.254546');});
test('opening suggestion exposes bounded eligible quantity',async()=>{const out=await suggestion(seed(),{itemGuid:'G-O',itemCode:'O',affectedQuantityExact:'12'});assert.equal(out.eligibleTargetQuantityExact,'10.000000');assert.equal(out.partialTarget,true);});
test('sale before opening date cannot consume opening basis',async()=>{const out=await manual.assistedSuggestion(seed(),{purchaseDatasetId:'P1',itemGuid:'G-O',itemCode:'O',applicableDate:'14040101'},actors.accounting);assert.equal(out.sourceClass,'NO_VALID_COST_BASIS');});
test('quantity mismatch and insignificant IRR display rounding do not reject authoritative opening evidence',async()=>{const db=seed();db.collection('openingInventoryEvidence').rows.push({evidenceId:'OI',status:'approved',itemGuid:'G-O',itemCode:'O',openingDate:'14050101',quantityExact:'15.000000',unitCostExact:'631958905.000000',contentHash:'x'});const out=await suggestion(db,{itemGuid:'G-O',itemCode:'O',affectedQuantityExact:'15'});assert.equal(out.sourceClass,'OPENING_ACCOUNTING_COST');assert.equal(out.suggestedCostExact,'631958905.254546');assert.equal(out.eligibleTargetQuantityExact,'10.000000');assert.equal(out.remainingUnknownQuantityExact,'5.000000');});
test('material opening unit-cost disagreement remains an explicit conflict',async()=>{const db=seed();db.collection('openingInventoryEvidence').rows.push({evidenceId:'OI',status:'approved',itemGuid:'G-O',itemCode:'O',quantityExact:'10',unitCostExact:'631958910'});assert.equal((await suggestion(db,{itemGuid:'G-O',itemCode:'O'})).sourceClass,'CONFLICT_REQUIRES_REVIEW');});
test('matching governed opening evidence does not create a conflict',async()=>{const db=seed();db.collection('openingInventoryEvidence').rows.push({evidenceId:'OI',status:'approved',itemGuid:'G-O',itemCode:'O',quantityExact:'10.000000',unitCostExact:'631958905.254546'});assert.equal((await suggestion(db,{itemGuid:'G-O',itemCode:'O'})).sourceClass,'OPENING_ACCOUNTING_COST');});
test('historical weighted average is third priority',async()=>{const out=await suggestion(seed(),{itemGuid:'G-H',itemCode:'H'});assert.equal(out.sourceClass,'HISTORICAL_PURCHASE_AVERAGE');assert.equal(out.suggestedCostExact,'160.000000');});
test('historical weighted evidence exposes and obeys quantity capacity',async()=>{const out=await suggestion(seed(),{itemGuid:'G-H',itemCode:'H',affectedQuantityExact:'8'});assert.equal(out.quantityBasisExact,'5.000000');assert.equal(out.eligibleTargetQuantityExact,'5.000000');assert.equal(out.remainingUnknownQuantityExact,'3.000000');assert.equal(out.evidenceQuality,'BROAD_ITEM_LEVEL_HISTORICAL_AVERAGE');});
test('future historical purchases are excluded',async()=>{assert.deepEqual((await suggestion(seed(),{itemGuid:'G-H',itemCode:'H'})).sourcePurchaseIds,['2','3']);});
test('unmatched return evidence is excluded from weighted average',async()=>{assert.equal((await suggestion(seed(),{itemGuid:'G-H',itemCode:'H'})).purchaseCount,2);});
test('mixed valid and pending one-rial history uses only eligible evidence and exposes exclusions',async()=>{const db=seed();db.collection('supplierPurchaseLayers').rows.push({datasetId:'P1',datasetSchemaVersion:1,purchaseLineIdentity:'HP',layerKind:'purchase',validationStatus:'warning',costStatus:'pending-purchase-price-correction',itemGuid:'G-H',itemCode:'H',purchaseInvoiceDate:'14040301',purchaseInvoiceNo:6,netPurchasedQuantityExact:'10',netUnitCostExact:'1',sourceHash:'p'});const out=await suggestion(db,{itemGuid:'G-H',itemCode:'H'});assert.equal(out.sourceClass,'HISTORICAL_PURCHASE_AVERAGE');assert.equal(out.suggestedCostExact,'160.000000');assert.equal(out.eligiblePurchaseCount,2);assert.equal(out.excludedPendingCount,1);assert.equal(out.excludedPendingQuantityExact,'10.000000');assert.deepEqual(out.excludedPurchaseIds,['6']);});
test('pending one-rial evidence alone is quarantined and cannot be finalized',async()=>{const db=seed();db.collection('itemCatalogAll').rows.push({itemCode:'P',itemGuid:'G-P',canonicalIdentity:'guid:g-p',historyCompleteness:'complete'});db.collection('supplierPurchaseLayers').rows.push({datasetId:'P1',datasetSchemaVersion:1,purchaseLineIdentity:'P1',layerKind:'purchase',validationStatus:'warning',costStatus:'pending-purchase-price-correction',itemGuid:'G-P',itemCode:'P',purchaseInvoiceDate:'14040301',purchaseInvoiceNo:7,netPurchasedQuantityExact:'2',netUnitCostExact:'1',sourceHash:'p'});const out=await suggestion(db,{itemGuid:'G-P',itemCode:'P'});assert.equal(out.sourceClass,'PENDING_PURCHASE_PRICE');assert.equal(out.available,false);assert.equal(out.excludedPendingCount,1);await assert.rejects(manual.assistedDecision(db,{decision:'APPROVE_OVERRIDE',purchaseDatasetId:'P1',itemGuid:'G-P',itemCode:'P',applicableDate:'14050501',effectiveFrom:'14050101',finalCost:'100',reason:'x'},actors.accounting),error=>error.code==='MANUAL_COST_PENDING_PURCHASE_PRICE');});
test('unlinked canonical purchase return blocks historical suggestion',async()=>{const db=seed();db.collection('supplierPurchaseLayers').rows.push({datasetId:'P1',datasetSchemaVersion:1,purchaseLineIdentity:'RET-H',layerKind:'purchase-return',validationStatus:'warning',returnMatchStatus:'unmatched',returnLinkageClass:'UNLINKED_RETURN',itemGuid:'G-H',itemCode:'H',purchaseInvoiceDate:'14040301',purchaseInvoiceNo:8,returnedQuantityExact:'1',sourceHash:'r'});const out=await suggestion(db,{itemGuid:'G-H',itemCode:'H'});assert.equal(out.sourceClass,'PURCHASE_RETURN_CONFLICT');assert.equal(out.available,false);await assert.rejects(manual.assistedDecision(db,{decision:'APPROVE_OVERRIDE',purchaseDatasetId:'P1',itemGuid:'G-H',itemCode:'H',applicableDate:'14050501',effectiveFrom:'14050101',finalCost:'100',reason:'x'},actors.accounting),error=>error.code==='MANUAL_COST_PURCHASE_RETURN_CONFLICT');});
test('absence of every source never becomes zero cost',async()=>{const out=await suggestion(seed(),{itemGuid:'G-N',itemCode:'N'});assert.equal(out.sourceClass,'NO_VALID_COST_BASIS');assert.equal(out.suggestedCostExact,null);});
test('incomplete catalog history blocks false no-cost classification and Manual Cost',async()=>{const db=seed();db.collection('itemCatalogAll').rows.push({itemCode:'I',itemGuid:'G-I',canonicalIdentity:'guid:gi',historyCompleteness:'incomplete'});const out=await suggestion(db,{itemGuid:'G-I',itemCode:'I'});assert.equal(out.sourceClass,'SOURCE_HISTORY_INCOMPLETE');assert.equal(out.evidenceComplete,false);await assert.rejects(manual.assistedDecision(db,{decision:'APPROVE_OVERRIDE',purchaseDatasetId:'P1',itemGuid:'G-I',itemCode:'I',applicableDate:'14050501',effectiveFrom:'14050101',finalCost:'100',reason:'x'},actors.accounting),error=>error.code==='MANUAL_COST_SOURCE_HISTORY_INCOMPLETE');});
for(const role of ['admin','accounting','purchase'])test(`${role} may finalize suggested evidence immediately`,async()=>{const db=seed();const out=await manual.assistedDecision(db,{decision:'APPROVE_SUGGESTED',purchaseDatasetId:'P1',itemGuid:'G-H',itemCode:'H',applicableDate:'14050501',effectiveFrom:'14050101'},actors[role]);assert.equal(out.resolution.status,'approved');assert.equal(out.resolution.approvedBy.role,role);assert.equal(out.adminApprovalRequired,false);});
for(const role of ['seller','manager'])test(`${role} may not finalize assisted evidence`,async()=>{await assert.rejects(manual.assistedDecision(seed(),{decision:'APPROVE_SUGGESTED',purchaseDatasetId:'P1',itemGuid:'G-H',itemCode:'H',applicableDate:'14050501',effectiveFrom:'14050101'},actors[role]),error=>error.code==='MANUAL_COST_FORBIDDEN');});
test('official exact source blocks Manual Cost finalization',async()=>{await assert.rejects(manual.assistedDecision(seed(),{decision:'APPROVE_SUGGESTED',purchaseDatasetId:'P1',itemGuid:'G-E',itemCode:'E',purchaseLineIdentity:'EXACT',applicableDate:'14050501',effectiveFrom:'14050101'},actors.accounting),error=>error.code==='MANUAL_COST_NOT_REQUIRED');});
test('source conflict blocks finalization',async()=>{const db=seed();db.collection('openingInventoryEvidence').rows.push({evidenceId:'OI',status:'approved',itemGuid:'G-O',quantityExact:'15',unitCostExact:'1'});await assert.rejects(manual.assistedDecision(db,{decision:'APPROVE_OVERRIDE',purchaseDatasetId:'P1',itemGuid:'G-O',itemCode:'O',applicableDate:'14050501',effectiveFrom:'14050101',effectiveTo:'14050501',affectedQuantityExact:'3',finalCost:'2',reason:'x'},actors.accounting),error=>error.code==='MANUAL_COST_SOURCE_CONFLICT');});
test('source conflict may be explicitly deferred without approved evidence or FIFO invalidation',async()=>{const db=seed();db.collection('openingInventoryEvidence').rows.push({evidenceId:'OI',status:'approved',itemGuid:'G-O',quantityExact:'15',unitCostExact:'1'});const out=await manual.assistedDecision(db,{decision:'DEFERRED',purchaseDatasetId:'P1',itemGuid:'G-O',itemCode:'O',applicableDate:'14050501',reason:'مأخذها باید توسط انسان تطبیق داده شوند'},actors.accounting);assert.equal(out.resolution.status,'draft');assert.equal(out.resolution.assistedStatus,'DEFERRED');assert.equal(out.fifoStale,false);assert.equal(db.collection('fifoSourceInvalidations').rows.length,0);});
test('opening acceptance creates bounded opening_quantity evidence, never fake purchase',async()=>{const out=await manual.assistedDecision(seed(),{decision:'APPROVE_SUGGESTED',purchaseDatasetId:'P1',itemGuid:'G-O',itemCode:'O',applicableDate:'14050501',effectiveFrom:'14050101',effectiveTo:'14050501',affectedQuantityExact:'3'},actors.accounting);assert.equal(out.resolution.resolutionScope,'opening_quantity');assert.equal(out.resolution.targetQuantityExact,'3.000000');assert.equal(out.resolution.purchaseLineIdentity,'');assert.equal(out.resolution.sourceType,'opening_accounting_cost');});
test('FIFO consumes governed opening quantity only and leaves later quantity unknown',()=>{const result=fifo._allocateSources('F-NEW',{saleActive:{snapshotId:'S1'},purchaseActive:{datasetId:'P1'},saleHeaders:[],saleLines:[{saleInvoiceType:2,saleInvoiceNo:1,row:1,saleLineId:'S1',saleDate:'14050102',itemGuid:'G-O',itemCode:'O',itemName:'Opening',qty:3,saleValue:900}],purchaseLayers:[],manuals:[{resolutionId:'M1',status:'approved',deleted:false,resolutionScope:'opening_quantity',itemGuid:'G-O',itemCode:'O',effectiveFrom:'14050101',effectiveTo:'14050131',targetQuantityExact:'2',manualCostExact:'100',contentHash:'a'.repeat(64),createdBy:actors.accounting,approvedBy:actors.accounting}],purchaseReturnResolutions:[],saleReturnResolutions:[]},{});assert.deepEqual(result.allocations.map(row=>[row.sourceType,row.allocatedQty,row.unknownQty]),[['approved_manual_opening_quantity',2,0],['unknown_cost',0,1]]);assert.equal(result.officialRows[0].purchaseInvoiceNo,0);assert.equal(result.officialRows[0].manualCostScope,'opening_quantity');});
test('bounded historical evidence is consumed deterministically and cannot exceed proven quantity',()=>{const source={saleActive:{snapshotId:'S1'},purchaseActive:{datasetId:'P1'},saleHeaders:[],saleLines:[{saleInvoiceType:2,saleInvoiceNo:1,row:1,saleLineId:'S1',saleDate:'14050102',itemGuid:'G-H',itemCode:'H',qty:3,saleValue:300},{saleInvoiceType:2,saleInvoiceNo:2,row:1,saleLineId:'S2',saleDate:'14050103',itemGuid:'G-H',itemCode:'H',qty:3,saleValue:300}],purchaseLayers:[],manuals:[{resolutionId:'M-H',status:'approved',deleted:false,resolutionScope:'evidence_quantity',sourceType:'historical_purchase',itemGuid:'G-H',itemCode:'H',effectiveFrom:'14050101',effectiveTo:'14050131',targetQuantityExact:'5',manualCostExact:'50',contentHash:'b'.repeat(64),createdBy:actors.accounting,approvedBy:actors.accounting}],purchaseReturnResolutions:[],saleReturnResolutions:[]};const a=fifo._allocateSources('F-A',structuredClone(source),{}),b=fifo._allocateSources('F-B',structuredClone(source),{});assert.deepEqual(a.allocations.map(row=>[row.saleLineId,row.sourceType,row.allocatedQty,row.unknownQty]),[['S1','approved_manual_evidence_quantity',3,0],['S2','approved_manual_evidence_quantity',2,0],['S2','unknown_cost',0,1]]);assert.deepEqual(a.allocations.map(row=>[row.saleLineId,row.sourceType,row.allocatedQty,row.unknownQty]),b.allocations.map(row=>[row.saleLineId,row.sourceType,row.allocatedQty,row.unknownQty]));});
test('override requires a reason',async()=>{await assert.rejects(manual.assistedDecision(seed(),{decision:'APPROVE_OVERRIDE',purchaseDatasetId:'P1',itemGuid:'G-H',itemCode:'H',applicableDate:'14050501',effectiveFrom:'14050101',finalCost:'170'},actors.purchase),error=>error.code==='MANUAL_COST_DECISION_REASON_REQUIRED');});
test('manual entry without source requires a reason',async()=>{await assert.rejects(manual.assistedDecision(seed(),{decision:'APPROVE_OVERRIDE',purchaseDatasetId:'P1',itemGuid:'G-N',itemCode:'N',applicableDate:'14050501',effectiveFrom:'14050101',finalCost:'170'},actors.admin),error=>error.code==='MANUAL_COST_DECISION_REASON_REQUIRED');});
test('finalization stores exposure actor role immutable hash and invalidation',async()=>{const db=seed();const out=await manual.assistedDecision(db,{decision:'APPROVE_SUGGESTED',purchaseDatasetId:'P1',itemGuid:'G-H',itemCode:'H',applicableDate:'14050501',effectiveFrom:'14050101',saleValueExposure:900,affectedLineCount:2,affectedQuantityExact:'3'},actors.purchase);assert.equal(out.resolution.saleValueExposure,900);assert.equal(out.resolution.affectedLineCount,2);assert.match(out.resolution.contentHash,/^[a-f0-9]{64}$/);assert.equal(db.collection('fifoSourceInvalidations').rows.length,1);});
test('suggestion path has no request-time Shaygan dependency',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/lib/manual-cost-resolution.js'),'utf8');const body=source.slice(source.indexOf('async function assistedSuggestion'),source.indexOf('async function assistedDecision'));assert.doesNotMatch(body,/getKardex|Invoice\/Get|require\(['"]\.\/shaygan/);assert.match(body,/openingCostBasis\.COLLECTION/);});
test('FSC has no operational accept override or finalize control',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/assets/financial-source-control.js'),'utf8');assert.match(source,/فقط گزارش و Audit/);assert.doesNotMatch(source,/fscCostAccept|fscCostOverride|manual-cost\/suggestion/);});
test('Manual Cost page is the sole operational Assisted UI',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/assets/app.js'),'utf8');assert.match(source,/بررسی و تعیین هزینه/);assert.match(source,/manual-cost-resolutions\/assisted\/suggestion/);assert.match(source,/manual-cost-resolutions\/assisted\/decisions/);});
test('conflict UI exposes both authoritative opening basis and governed evidence',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/assets/app.js'),'utf8');assert.match(source,/مأخذ رسمی شایگان/);assert.match(source,/openingEvidence\?\.openingQuantityExact/);assert.match(source,/Opening Inventory Evidence متعارض/);});
test('suggestion and impact UI expose bounded quantities with collapsed technical JSON',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/assets/app.js'),'utf8');for(const label of ['قیمت پیشنهادی سیستم','مقدار قابل پوشش با این مأخذ','کل مقدار نیازمند تعیین هزینه','مقدار باقی‌مانده بدون مأخذ','اثر تصمیم','جزئیات فنی'])assert.match(source,new RegExp(label));assert.match(source,/<details><summary>جزئیات فنی<\/summary>/);});
test('queue renders before secondary panels and filter refresh does not fan out',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/assets/app.js'),'utf8');assert.match(source,/async function refreshAll\(\)\{await loadQueue\(\);await Promise\.all/);assert.match(source,/mcApply'\)\.onclick=\(\)=>\{queuePage=1;loadQueue\(\);\}/);});
test('Procurement can reach only the canonical Manual Cost operational page',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/assets/app.js'),'utf8');assert.match(source,/purchase: \[[^\]]*'manual-cost-resolution'/);assert.match(source,/currentRole==='purchase'/);assert.match(source,/add\(menu,\{id:'manual-cost-resolution'/);});
test('server exposes one operational Assisted route family',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/server.js'),'utf8');assert.equal((source.match(/manual-cost-resolutions\/assisted\/decisions/g)||[]).length,1);assert.doesNotMatch(source,/financial-source-control\/manual-cost\/decisions'&&req\.method==='POST/);});
test('opening materializer is diagnostic and does not write Purchase or FIFO collections',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/lib/opening-accounting-cost-basis.js'),'utf8');assert.doesNotMatch(source,/supplierPurchaseLayers.*(?:insert|update)|fifoAllocations.*(?:insert|update)/);assert.match(source,/readOnlySource:true,purchaseLayerWrites:0,fifoWrites:0/);});
