'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {MemoryDb}=require('./helpers/memory-mongo');
const batches=require('../src/lib/profit-adjustment-batches');
const ledger=require('../src/lib/profit-commission-ledger');
const sellerFinancial=require('../src/lib/seller-financial-performance');

const accounting={username:'accounting-a',role:'accounting'};
const manager={username:'manager-a',role:'manager'};
const admin={username:'admin-a',role:'admin'};
const seller={username:'seller-a',role:'seller'};

function line(overrides={}){return{runId:'RUN-1',saleLineIdentity:'LINE-1',saleInvoiceIdentity:'2:100',saleInvoiceNumber:100,saleDate:'14050410',sellerIdentity:'11701013',sellerName:'Seller A',storeIdentity:'STORE-1',storeName:'Store 1',itemCode:'NB-1',itemDescription:'Notebook',officialProductCategoryIdentity:'guid:NOTEBOOK',officialProductCategoryName:'NOTEBOOK',commissionRatePool:'NOTEBOOK',policyVersionId:'POLICY-1',policyAvailability:'available',categoryMappingId:'MAP-1',categoryAvailability:'available',rateVersionId:'RATE-1',rateAvailability:'available',grossSaleAmountExact:'1000.00',invoiceGrossSaleAmountExact:'2000.00',actualFifoProfitExact:'100.00',approvedAdjustmentAmountExact:'0.00',lineDiscountExact:'10.00',allocatedInvoiceDiscountExact:'0.00',discountAvailability:'available',costCoverageStatus:'complete',lineFingerprint:'a'.repeat(64),...overrides};}
function dbSeed(extra={}){return new MemoryDb({
  sellerFinancialPerformanceState:[{scopeKey:sellerFinancial.SCOPE_KEY,activeRunId:'RUN-1',sourceFingerprint:'SOURCE-1'}],
  sellerFinancialPerformanceRuns:[{runId:'RUN-1',status:'completed',activationStatus:'active',sourceFifoDatasetId:'FIFO-1',sourceFingerprint:'SOURCE-1',resultFingerprint:'b'.repeat(64)}],
  sellerFinancialPerformanceLines:[line(),line({saleLineIdentity:'LINE-2',itemCode:'NB-2',actualFifoProfitExact:'300.00',lineDiscountExact:'0.00',lineFingerprint:'c'.repeat(64)})],
  fifoProfitFacts:[{factId:'F1',fifoDatasetId:'FIFO-1',saleLineIdentity:'LINE-1',actualFifoProfitExact:'100.00',immutable:true},{factId:'F2',fifoDatasetId:'FIFO-1',saleLineIdentity:'LINE-2',actualFifoProfitExact:'300.00',immutable:true}],
  commissionPolicyVersions:[{policyVersionId:'POLICY-1',status:'approved'}],commissionCategoryMappings:[{mappingId:'MAP-1',status:'approved'}],commissionRateVersions:[{rateVersionId:'RATE-1',status:'approved'}],
  savedProfitLedgerEntries:[],profitAdjustments:[],profitAdjustmentBatches:[],profitAdjustmentBatchAllocations:[],...extra
});}
function payload(overrides={}){return{classification:'BUSINESS',policyVersionId:'POLICY-1',accountingPeriod:'140504',sellerIdentity:'11701013',officialProductCategoryIdentity:'guid:NOTEBOOK',officialProductCategoryName:'NOTEBOOK',commissionRatePool:'NOTEBOOK',candidateLineIds:['LINE-1','LINE-2'],selectedInvoiceIds:['2:100'],selectedLineIds:['LINE-1','LINE-2'],adjustmentMode:'high_profit_reduction',targetMethod:'target_commissionable_profit_per_invoice',targetValueExact:'200.00',filterSnapshot:{dateFrom:'14050401',dateTo:'14050431'},...overrides};}
async function createAndPreview(db,input={}){const created=await batches.createDraft(db,payload(input),accounting);const preview=await batches.preview(db,created.batch.batchId,{revision:created.batch.revision,selectedLineIds:payload(input).selectedLineIds,targetValueExact:payload(input).targetValueExact},accounting);return preview;}
async function submit(db,preview){return batches.transition(db,preview.batch.batchId,'submit',{revision:preview.batch.revision,reason:'TEST-CODEX-PHASE-D-20260805-WORKFLOW'},accounting);}

test('candidate analysis is read-only and exposes exact immutable FIFO and official discounts',async()=>{const db=dbSeed();const before=structuredClone(db.collection('fifoProfitFacts').rows);const result=await batches.candidates(db,{completeCostOnly:true},accounting);assert.equal(result.total,2);assert.equal(result.list[0].baseCommissionableProfitExact,'90.00');assert.deepEqual(db.collection('fifoProfitFacts').rows,before);await assert.rejects(batches.candidates(db,{},seller),error=>error.code==='PROFIT_BATCH_FORBIDDEN');});

test('Preview is mandatory and target/selection regeneration changes the fingerprint',async()=>{const db=dbSeed();const created=await batches.createDraft(db,payload(),accounting);await assert.rejects(batches.transition(db,created.batch.batchId,'submit',{revision:1,reason:'no preview'},accounting),error=>error.code==='PROFIT_BATCH_TRANSITION_INVALID');const first=await batches.preview(db,created.batch.batchId,{revision:1,selectedLineIds:['LINE-1','LINE-2'],targetValueExact:'200'},accounting);const second=await batches.preview(db,created.batch.batchId,{revision:first.batch.revision,selectedLineIds:['LINE-1','LINE-2'],targetValueExact:'210'},accounting);assert.notEqual(first.batch.previewFingerprint,second.batch.previewFingerprint);assert.equal(second.batch.expectedCreditExact,'180.00');assert.equal(db.collection(batches.ALLOCATIONS).rows.length,4);assert.equal(new Set(db.collection(batches.ALLOCATIONS).rows.map(row=>row.previewFingerprint)).size,2);});

test('high-profit reduction uses deterministic largest remainder and exact child sum',async()=>{const db=dbSeed();const before=structuredClone(db.collection('fifoProfitFacts').rows);const result=await createAndPreview(db);assert.equal(result.batch.expectedCreditExact,'190.00');assert.equal(result.invoicePreviews[0].baseCommissionableProfitExact,'390.00');assert.equal(result.invoicePreviews[0].childSumExact,'190.00');assert.deepEqual(result.allocations.map(row=>row.allocatedAmountExact),['47.50','142.50']);const replay=batches._largestRemainder('190.00',db.collection(sellerFinancial.LINES).rows,'positive_actual_fifo_profit');assert.deepEqual(replay.map(row=>row.allocatedAmountExact),['47.50','142.50']);assert.deepEqual(db.collection('fifoProfitFacts').rows,before);});

test('unknown/partial cost and missing governance are denied rather than treated as zero',async()=>{for(const patch of [{costCoverageStatus:'partial'},{actualFifoProfitExact:null},{policyAvailability:'unavailable',policyVersionId:''},{categoryAvailability:'unavailable',categoryMappingId:''},{rateAvailability:'unavailable',rateVersionId:''}]){const db=dbSeed({sellerFinancialPerformanceLines:[line(patch)]});const created=await batches.createDraft(db,payload({selectedLineIds:['LINE-1'],candidateLineIds:['LINE-1']}),accounting);await assert.rejects(batches.preview(db,created.batch.batchId,{revision:1,selectedLineIds:['LINE-1'],targetValueExact:'1'},accounting),error=>['PROFIT_BATCH_INELIGIBLE_LINES','PROFIT_BATCH_SELECTION_SCOPE_EMPTY'].includes(error.code));assert.equal(db.collection(ledger.ADJUSTMENTS).rows.length,0);}});

test('invoice-wide selection blocks multi-category invoices but explicit scoped lines remain allowed',async()=>{const db=dbSeed({sellerFinancialPerformanceLines:[line(),line({saleLineIdentity:'LINE-2',officialProductCategoryIdentity:'guid:CPU',officialProductCategoryName:'CPU',commissionRatePool:'COMPONENT',policyVersionId:'POLICY-1',categoryMappingId:'MAP-CPU',rateVersionId:'RATE-CPU'})]});const created=await batches.createDraft(db,payload({selectedLineIds:[],selectedInvoiceIds:['2:100']}),accounting);await assert.rejects(batches.preview(db,created.batch.batchId,{revision:1,selectedLineIds:[],selectedInvoiceIds:['2:100'],targetValueExact:'20'},accounting),error=>error.code==='PROFIT_BATCH_MULTI_CATEGORY_INVOICE');});

test('subsidy counts pending reservations and isolates NOTEBOOK from COMPONENT',async()=>{const opening={ledgerEntryId:'OPEN-NB',pool:'NOTEBOOK',accountingPeriod:'140504',entryType:'opening_balance',creditAmountExact:'200.00',debitAmountExact:'0.00'};const db=dbSeed({savedProfitLedgerEntries:[opening]});const first=await createAndPreview(db,{adjustmentMode:'low_profit_subsidy',targetValueExact:'500'});assert.equal(first.batch.expectedDebitExact,'110.00');const pending=await submit(db,first);assert.equal(pending.batch.status,'pending');const secondCreated=await batches.createDraft(db,payload({adjustmentMode:'low_profit_subsidy',targetValueExact:'500'}),accounting);await assert.rejects(batches.preview(db,secondCreated.batch.batchId,{revision:1,selectedLineIds:['LINE-1','LINE-2'],targetValueExact:'500'},accounting),error=>error.code==='PROFIT_BATCH_INSUFFICIENT_BALANCE');const statement=await batches.monthlyStatement(db,{accountingPeriod:'140504'},accounting);assert.equal(statement.statements.find(row=>row.pool==='NOTEBOOK').pendingDebitReservationsExact,'110.00');assert.equal(statement.statements.find(row=>row.pool==='COMPONENT').availableApprovedBalanceExact,'0.00');});

test('approval is independent, revision-guarded, idempotent and posts only adjustment/ledger rows',async()=>{const db=dbSeed();const facts=structuredClone(db.collection('fifoProfitFacts').rows);const preview=await createAndPreview(db);const pending=await submit(db,preview);await assert.rejects(batches.approve(db,pending.batch.batchId,{revision:99,reason:'stale'},manager),error=>error.code==='PROFIT_BATCH_CONFLICT');await assert.rejects(batches.approve(db,pending.batch.batchId,{revision:pending.batch.revision,reason:'self'},accounting),error=>error.code==='PROFIT_BATCH_FORBIDDEN');const posted=await batches.approve(db,pending.batch.batchId,{revision:pending.batch.revision,reason:'independent approval'},manager);assert.equal(posted.batch.status,'posted');assert.equal(posted.postedAdjustments,2);assert.equal(posted.postedLedgerEntries,2);assert.equal(db.collection(ledger.ADJUSTMENTS).rows.every(row=>row.status==='approved'&&row.classification==='BUSINESS'),true);assert.equal((await batches.monthlyStatement(db,{accountingPeriod:'140504',pool:'NOTEBOOK'},manager)).statement.closingBalanceExact,'190.00');assert.deepEqual(db.collection('fifoProfitFacts').rows,facts);const replay=await batches.postApproved(db,pending.batch.batchId);assert.equal(replay.idempotent,true);assert.equal(db.collection(ledger.SAVED_LEDGER).rows.length,2);});

test('posting recovers idempotently from crash after adjustment or ledger insert',async()=>{for(const injectFailure of ['after-adjustment','after-ledger']){const db=dbSeed();const pending=await submit(db,await createAndPreview(db));await assert.rejects(batches.approve(db,pending.batch.batchId,{revision:pending.batch.revision,reason:'controlled recovery'},manager,{injectFailure}),error=>error.code==='INJECTED_POSTING_FAILURE');const failed=db.collection(batches.BATCHES).rows.find(row=>row.batchId===pending.batch.batchId);assert.equal(failed.status,'post_failed_retryable');const recovered=await batches.postApproved(db,pending.batch.batchId);assert.equal(recovered.batch.status,'posted');assert.equal(db.collection(ledger.ADJUSTMENTS).rows.length,2);assert.equal(db.collection(ledger.SAVED_LEDGER).rows.length,2);}});

test('posted batch reversal requires a second independent approval and remains append-only',async()=>{const db=dbSeed();const pending=await submit(db,await createAndPreview(db));const posted=await batches.approve(db,pending.batch.batchId,{revision:pending.batch.revision,reason:'independent approval'},manager);const requested=await batches.requestReversal(db,posted.batch.batchId,{revision:posted.batch.revision,reason:'TEST-CODEX-PHASE-D-20260805-REVERSAL'},accounting);await assert.rejects(batches.approveReversal(db,posted.batch.batchId,{revision:requested.batch.revision,reason:'self'},accounting),error=>error.code==='PROFIT_BATCH_FORBIDDEN');const reversed=await batches.approveReversal(db,posted.batch.batchId,{revision:requested.batch.revision,reason:'independent reversal approval'},admin);assert.equal(reversed.batch.status,'reversed');assert.equal(db.collection(ledger.SAVED_LEDGER).rows.length,4);assert.equal(db.collection(ledger.ADJUSTMENTS).rows.every(row=>row.status==='reversed'),true);assert.equal((await batches.monthlyStatement(db,{accountingPeriod:'140504',pool:'NOTEBOOK'},manager)).statement.closingBalanceExact,'0.00');assert.equal((await batches.approveReversal(db,posted.batch.batchId,{revision:reversed.batch.revision},admin)).idempotent,true);});

test('classification, cancellation, seller denial and no physical delete contracts are explicit',async()=>{const db=dbSeed();await assert.rejects(batches.createDraft(db,payload({classification:'UNKNOWN'}),accounting),error=>error.code==='PROFIT_BATCH_CLASSIFICATION_REQUIRED');const created=await batches.createDraft(db,payload({classification:'TEST'}),accounting);const cancelled=await batches.transition(db,created.batch.batchId,'cancel',{revision:1,reason:'TEST-CODEX-PHASE-D-20260805-CANCEL'},accounting);assert.equal(cancelled.batch.status,'cancelled');assert.equal(db.collection(batches.BATCHES).rows.length,1);const list=await batches.listBatches(db,{},manager);assert.equal(list.physicalDeleteAllowed,false);assert.equal(list.list[0].classification,'TEST');});

test('TEST posting and BUSINESS use of test-classified governance remain blocked by default',async()=>{const db=dbSeed();const testPreview=await createAndPreview(db,{classification:'TEST'});await assert.rejects(batches.transition(db,testPreview.batch.batchId,'submit',{revision:testPreview.batch.revision,reason:'attempt'},accounting),error=>error.code==='PROFIT_BATCH_TEST_POSTING_NOT_AUTHORIZED');db.collection('commissionPolicyVersions').rows[0].name='TEST-CODEX-PHASE-D-20260805-POLICY';const business=await batches.createDraft(db,payload(),accounting);await assert.rejects(batches.preview(db,business.batch.batchId,{revision:1,selectedLineIds:['LINE-1','LINE-2'],targetValueExact:'200'},accounting),error=>error.code==='PROFIT_BATCH_BUSINESS_GOVERNANCE_REQUIRED');assert.equal(db.collection(ledger.ADJUSTMENTS).rows.length,0);assert.equal(db.collection(ledger.SAVED_LEDGER).rows.length,0);});

test('health confirms no FIFO, invoice, Shaygan or payable commission write surface',async()=>{const result=await batches.health(dbSeed());assert.deepEqual(result.safety,{actualFifoImmutable:true,unknownCostIsZero:false,payableCommission:false,sellerFacing:false,sourceWrites:0,shayganWrites:0,invoiceWrites:0,crossPoolTransfers:false});});

test('governed record report classifies every record with visible evidence and current effect',async()=>{const db=dbSeed({commissionPolicyVersions:[{policyVersionId:'LEGACY_PRE_POLICY',name:'Pre-policy',status:'historical_frozen',createdBy:{username:'phase-b-migration',role:'admin'}},{policyVersionId:'POLICY-1',name:'TEST-CODEX-PHASE-D-20260805-POLICY',status:'approved',createdBy:accounting}],commissionCategoryMappings:[{mappingId:'MAP-1',policyVersionId:'POLICY-1',status:'approved',createdBy:accounting}],commissionRateVersions:[{rateVersionId:'RATE-1',policyVersionId:'POLICY-1',status:'pending',createdBy:accounting}]});const report=await batches.classificationReport(db,manager);assert.equal(report.records.length>=4,true);assert.equal(report.records.find(row=>row.recordId==='LEGACY_PRE_POLICY').classification,'HISTORICAL');const mapping=report.records.find(row=>row.recordId==='MAP-1');assert.equal(mapping.classification,'TEST');assert.equal(mapping.affectsCurrentCalculations,true);assert.equal(mapping.cleanupOrReversalRequired,true);assert.equal(report.noSilentOwnershipInference,true);});

test('Phase D UI is Persian, explicit, non-payable and contains no browser prompt workflow',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/assets/app.js'),'utf8');const block=source.slice(source.indexOf('/* Phase D — governed Commissionable'),source.indexOf('/* Phase B financial-governance',source.indexOf('/* Phase D — governed Commissionable')));for(const label of ['سود واقعی FIFO غیرقابل تغییر است','سود مبنای پورسانت','سود ذخیره‌شده','سود مصرف‌شده','مانده قابل استفاده','Preview اجباری است'])assert.equal(block.includes(label),true,label);assert.equal(block.includes('prompt('),false);assert.equal(block.includes('confirm('),false);assert.equal(block.includes("ALLOWED=['admin','accounting','manager']"),true);});
