'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {MemoryDb}=require('./helpers/memory-mongo');
const fsc=require('../src/lib/financial-source-control');

const accounting={username:'khedmati',role:'accounting'};
const layer=(overrides={})=>({datasetId:'PLAYER-REVIEW',datasetSchemaVersion:1,purchaseLineIdentity:'L-BASE',layerKind:'purchase',sourceInvoiceType:3,purchaseInvoiceGuid:'INV-GUID',purchaseInvoiceNo:1,purchaseInvoiceDate:'14050105',sourceRow:1,itemGuid:'G-BASE',itemCode:'BASE',itemDescription:'Base item',supplierGuid:'S-GUID',supplierAccountNumber:'11801015',supplierName:'Supplier',originalQuantity:1,returnedQuantity:0,netPurchasedQuantity:1,grossUnitCost:100,netUnitCost:100,costStatus:'known-from-shaygan-line',validationStatus:'valid',validationWarnings:[],returnMatchStatus:'not-applicable',returnLinkageClass:'NOT_APPLICABLE',linkedReturnIdentities:[],sourceHash:'a'.repeat(64),...overrides});
function seed(){return new MemoryDb({
  purchaseLayerDatasetState:[],
  purchaseLayerDatasets:[
    {datasetId:'PLAYER-OLD',status:'completed',activationStatus:'historical',sourceDateFrom:'14040101',sourceDateTo:'14041229',sourceFingerprint:'OLD',layerFingerprint:'OLD-L',validation:{valid:true},completedAt:new Date('2026-08-01')},
    {datasetId:'PLAYER-REVIEW',status:'completed',activationStatus:'validated-candidate',sourceDateFrom:'14050101',sourceDateTo:'14050606',sourceFingerprint:'SOURCE',layerFingerprint:'LAYER',validation:{valid:true},completedAt:new Date('2026-08-27')}
  ],
  supplierPurchaseLayers:[
    layer({purchaseLineIdentity:'P01',purchaseInvoiceNo:1,itemGuid:'G-P01',itemCode:'8011WMP400',originalQuantity:1,netPurchasedQuantity:1,grossUnitCost:245000000,netUnitCost:245000000}),
    layer({purchaseLineIdentity:'P02',purchaseInvoiceNo:533,purchaseInvoiceDate:'14050304',itemGuid:'G-P02',itemCode:'700LF',supplierAccountNumber:'11801006',supplierName:'ایلیا - عندلیب نقدی',originalQuantity:20,returnedQuantity:10,netPurchasedQuantity:10,grossUnitCost:200000,netUnitCost:200000,returnMatchStatus:'matched',returnLinkageClass:'EXACT_ORIGIN_LINK',linkedReturnIdentities:['R02']}),
    layer({purchaseLineIdentity:'R02',layerKind:'purchase-return',sourceInvoiceType:7,purchaseInvoiceNo:16,purchaseInvoiceDate:'14050310',itemGuid:'G-P02',itemCode:'700LF',supplierAccountNumber:'11801006',supplierName:'ایلیا - عندلیب نقدی',originalQuantity:0,returnedQuantity:10,netPurchasedQuantity:null,grossUnitCost:null,netUnitCost:null,costStatus:'not-applicable-return-row',returnMatchStatus:'matched',returnLinkageClass:'EXACT_ORIGIN_LINK',matchedPurchaseLineIdentity:'P02'}),
    layer({purchaseLineIdentity:'P04-A',purchaseInvoiceGuid:'P04-G',sourceInvHeaderId:'P04-H',purchaseInvoiceNo:676,purchaseInvoiceDate:'14050401',itemGuid:'G-P04',itemCode:'7997TP0001',supplierAccountNumber:'41107006',supplierName:'طوس همراه',sourceRow:1,originalQuantity:4,netPurchasedQuantity:4,grossUnitCost:8696138.75,netUnitCost:8696138.75}),
    layer({purchaseLineIdentity:'P04-B',purchaseInvoiceGuid:'P04-G',sourceInvHeaderId:'P04-H',purchaseInvoiceNo:676,purchaseInvoiceDate:'14050401',itemGuid:'G-P04',itemCode:'7997TP0001',supplierAccountNumber:'41107006',supplierName:'طوس همراه',sourceRow:2,originalQuantity:15,netPurchasedQuantity:15,grossUnitCost:2114696.3333333,netUnitCost:2114696.3333333}),
    layer({purchaseLineIdentity:'R04',layerKind:'purchase-return',sourceInvoiceType:7,purchaseInvoiceNo:21,purchaseInvoiceDate:'14050410',itemGuid:'G-P04',itemCode:'7997TP0001',supplierAccountNumber:'41107006',supplierName:'طوس همراه',returnPurchaseInvoiceNoReference:'676',originalQuantity:0,returnedQuantity:15,netPurchasedQuantity:null,grossUnitCost:null,netUnitCost:null,costStatus:'not-applicable-return-row',validationStatus:'warning',returnMatchStatus:'ambiguous',returnLinkageClass:'AMBIGUOUS_RETURN'}),
    layer({purchaseLineIdentity:'P05',purchaseInvoiceNo:1615,purchaseInvoiceDate:'14050605',itemGuid:'G-P05',itemCode:'19STH59870',supplierAccountNumber:'11804019',supplierName:'فروشنده استوک',originalQuantity:1,netPurchasedQuantity:1,grossUnitCost:1,netUnitCost:1,costStatus:'pending-purchase-price-correction',validationStatus:'warning'}),
    layer({purchaseLineIdentity:'P06-A',purchaseInvoiceNo:398,purchaseInvoiceDate:'14050201',itemGuid:'G-P06',itemCode:'10F6087945',originalQuantity:1,netPurchasedQuantity:1,grossUnitCost:3710300000,netUnitCost:3710300000}),
    layer({purchaseLineIdentity:'P06-B',purchaseInvoiceNo:1567,purchaseInvoiceDate:'14050601',itemGuid:'G-P06',itemCode:'10F6087945',originalQuantity:3,netPurchasedQuantity:3,grossUnitCost:3510000000,netUnitCost:3510000000}),
    layer({purchaseLineIdentity:'P06-X',purchaseInvoiceNo:1607,purchaseInvoiceDate:'14050604',itemGuid:'G-P06',itemCode:'10F6087945',originalQuantity:3,netPurchasedQuantity:3,grossUnitCost:1,netUnitCost:1,costStatus:'pending-purchase-price-correction',validationStatus:'warning'}),
    layer({purchaseLineIdentity:'P07',purchaseInvoiceNo:1700,purchaseInvoiceDate:'14050601',itemGuid:'G-P07',itemCode:'11I0158200',originalQuantity:5,netPurchasedQuantity:5,grossUnitCost:100,netUnitCost:100})
  ],
  saleSnapshotState:[{scopeKey:'sale',activeSnapshotId:'SSALE-A',activatedAt:new Date('2026-08-27')}],
  saleSnapshots:[{snapshotId:'SSALE-A',status:'completed'}],
  saleSnapshotDatasetLines:[
    {snapshotId:'SSALE-A',saleInvoiceType:2,saleInvoiceNo:1,row:1,saleLineId:'S-P06',saleDate:'14050605',itemGuid:'G-P06',itemCode:'10F6087945',itemName:'P06',qty:7,saleValue:1000},
    {snapshotId:'SSALE-A',saleInvoiceType:2,saleInvoiceNo:2,row:1,saleLineId:'S-P07',saleDate:'14050605',itemGuid:'G-P07',itemCode:'11I0158200',itemName:'P07',qty:21,saleValue:2000}
  ],
  manualCostResolutions:[],itemCatalogAll:[],itemInventoryCatalog:[],openingCostBasis:[],openingInventoryEvidence:[]
});}

test('latest validated Purchase Candidate is the default read-only Dataset',async()=>{const out=await fsc.purchaseAuditDatasets(seed(),{},accounting);assert.equal(out.defaultDatasetId,'PLAYER-REVIEW');assert.equal(out.list[0].badge,'VALIDATED_CANDIDATE');assert.equal(out.readOnly,true);});
test('eligible, pending and return-conflict views are separate and bounded',async()=>{const db=seed();const eligible=await fsc.purchaseAuditRows(db,{datasetId:'PLAYER-REVIEW',view:'eligible',itemCode:'8011WMP400'},accounting),pending=await fsc.purchaseAuditRows(db,{datasetId:'PLAYER-REVIEW',view:'pending',itemCode:'19STH59870'},accounting),returns=await fsc.purchaseAuditRows(db,{datasetId:'PLAYER-REVIEW',view:'returns',returnInvoiceNumber:'21'},accounting);assert.equal(eligible.total,1);assert.equal(eligible.list[0].unitCostExact,'245000000');assert.equal(pending.list[0].costStatus,'pending-purchase-price-correction');assert.equal(returns.list[0].returnLinkageClass,'AMBIGUOUS_RETURN');});
test('PUR-P02 drill-down exposes purchase, exact return and eligible capacity',async()=>{const out=await fsc.purchaseAuditDetail(seed(),{datasetId:'PLAYER-REVIEW',purchaseLineIdentity:'P02'},accounting);assert.equal(out.purchase.originalQuantityExact,'20');assert.equal(out.purchase.returnedQuantityExact,'10');assert.equal(out.purchase.eligibleQuantityExact,'10');assert.equal(out.returns[0].invoiceNumber,16);assert.equal(out.returns[0].returnLinkageClass,'EXACT_ORIGIN_LINK');});
test('PUR-P04 ambiguity shows every possible origin without reducing capacity',async()=>{const out=await fsc.purchaseAuditDetail(seed(),{datasetId:'PLAYER-REVIEW',purchaseLineIdentity:'R04'},accounting);assert.equal(out.returns[0].returnLinkageClass,'AMBIGUOUS_RETURN');assert.equal(out.possibleOrigins.length,2);assert.equal(out.capacityAutomaticallyReduced,false);});
test('PUR-P06 weighted evidence excludes one-rial pending Purchase',async()=>{const out=await fsc.purchaseAuditItemSummary(seed(),{datasetId:'PLAYER-REVIEW',itemCode:'10F6087945',itemGuid:'G-P06'},accounting);assert.equal(out.validQuantityExact,'4.000000');assert.equal(out.excludedQuantityExact,'3.000000');assert.equal(out.requiredQuantityExact,'7.000000');assert.equal(out.remainingUnknownQuantityExact,'3.000000');assert.equal(out.weightedValidCostExact,'3560075000.000000');assert.deepEqual(out.validPurchaseIds,['398','1567']);assert.deepEqual(out.excludedPurchaseIds,['1607']);});
test('PUR-P07 visibly caps evidence at five of twenty-one units',async()=>{const out=await fsc.purchaseAuditItemSummary(seed(),{datasetId:'PLAYER-REVIEW',itemCode:'11I0158200',itemGuid:'G-P07'},accounting);assert.equal(out.requiredQuantityExact,'21.000000');assert.equal(out.coveredQuantityExact,'5.000000');assert.equal(out.remainingUnknownQuantityExact,'16.000000');});
test('all Purchase Human Review reads preserve Candidate collections byte-for-byte',async()=>{const db=seed(),before=JSON.stringify(db.collection('supplierPurchaseLayers').rows);await fsc.purchaseAuditDatasets(db,{},accounting);await fsc.purchaseAuditRows(db,{datasetId:'PLAYER-REVIEW',view:'eligible'},accounting);await fsc.purchaseAuditDetail(db,{datasetId:'PLAYER-REVIEW',purchaseLineIdentity:'P02'},accounting);await fsc.purchaseAuditItemSummary(db,{datasetId:'PLAYER-REVIEW',itemCode:'10F6087945'},accounting);assert.equal(JSON.stringify(db.collection('supplierPurchaseLayers').rows),before);});
test('Purchase Human Review UI is Persian-first and contains no activation or review mutation',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/assets/financial-source-control.js'),'utf8');for(const value of ['لایه‌های خرید قابل استفاده','قیمت خرید در انتظار اصلاح','مغایرت/ابهام برگشت از خرید','هیچ ظرفیت خریدی به‌صورت خودکار کاهش نیافته است','خلاصه شواهد هزینه کالا'])assert.match(source,new RegExp(value));const section=source.slice(source.indexOf('async function purchaseTab'),source.indexOf('async function lineAction'));assert.doesNotMatch(section,/line-actions|activate|fscLineReviewed|fscLineMismatch/);});
test('Purchase review server routes are GET-only and invoke no Shaygan source',()=>{const server=fs.readFileSync(path.join(__dirname,'../src/server.js'),'utf8'),service=fs.readFileSync(path.join(__dirname,'../src/lib/financial-source-control.js'),'utf8');for(const route of ['purchase/datasets','purchase/rows','purchase/detail','purchase/item-summary'])assert.match(server,new RegExp(route.replace('/','\\/')));assert.doesNotMatch(service,/require\(['"]\.\/shaygan['"]\)|Invoice\/Get|GetKardex/);});
