'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const {MemoryDb}=require('./helpers/memory-mongo');
const issuance=require('../src/lib/sale-invoice-issuance');

const seller={username:'seller-a',role:'seller'};
const accounting={username:'accounting-a',role:'accounting'};
const admin={username:'admin-a',role:'admin'};
const mapping={username:'seller-a',fullName:'Seller A',storeName:'Store 1',cashboxAccountNumber:'CASH-1',employeeAccountNumber:'SELLER-1'};
const body={customerName:'Customer A',mobile:'09120000000',nationalCode:'0012345678',leadId:'LEAD-1',invDate:'14050514',discountAmount:10,generalRef:'REF-1',items:[{itemCode:'I-1',itemGuid:'IG-1',stockNumber:'1',stockGuid:'SG-1',quantity:2,price:100,serials:['S-1']},{itemCode:'I-2',itemGuid:'IG-2',stockNumber:'1',stockGuid:'SG-1',quantity:1,price:50}],invoiceExtras:[{accountNumber:'EX-1',accountGuid:'EG-1',amount:5,type:'delivery'}]};
function db(){return new MemoryDb({saleIssueLocks:[],saleIssuanceFingerprintLocks:[],invoiceAuditLogs:[]});}
async function prepared(database,id='browser-a'){return issuance.beginAttempt(database,{attemptId:id,body,mapping,user:seller,applicationVersion:'hotfix',gitSha:'a'.repeat(40),at:new Date('2026-08-05T10:00:00Z')});}

test('A: Put success and immediate resolve records one Put and resolved identity',async()=>{const database=db(),created=await prepared(database);await issuance.markPutInProgress(database,created.attempt._id,seller);await issuance.markPutSucceededResolvePending(database,created.attempt._id,{httpStatus:200,identifiers:{invoiceGuid:'G-1'},resolveEnvelope:{ok:true,result:[{GuId:'G-1'}]}},seller);const resolved=await issuance.markResolved(database,created.attempt._id,{invoiceNumber:123,invoiceGuid:'G-1',result:{Number:123,GuId:'G-1'},printUrl:'/print/invoice/123'},seller);assert.equal(resolved.issuanceState,'resolved');assert.equal(resolved.putCallCount,1);assert.equal(issuance.publicAttempt(resolved).invoiceNumber,123);});

test('B/C/N: timeout or lost response stays locked and repeated submission never permits a second Put',async()=>{for(const reason of ['timeout','connection-lost']){const database=db(),first=await prepared(database,`attempt-${reason}`);await issuance.markPutInProgress(database,first.attempt._id,seller);const ambiguous=await issuance.markAmbiguous(database,first.attempt._id,{error:reason,httpStatus:0},seller);const repeated=await issuance.beginAttempt(database,{attemptId:`attempt-${reason}`,body,mapping,user:seller});const otherBrowser=await issuance.beginAttempt(database,{attemptId:`other-${reason}`,body,mapping,user:seller});assert.equal(ambiguous.putCallCount,1);assert.equal(repeated.mayPut,false);assert.equal(otherBrowser.mayPut,false);assert.equal(otherBrowser.fingerprintMatch,true);assert.equal(otherBrowser.attempt._id,first.attempt._id);assert.equal(issuance.publicAttempt(ambiguous).issuanceLocked,true);}});

test('D/K/O: ambiguous invoice can be resolved by read-only retry without another Put',async()=>{const database=db(),first=await prepared(database);await issuance.markPutInProgress(database,first.attempt._id,seller);await issuance.markAmbiguous(database,first.attempt._id,{error:'lost'},seller);const retry=await issuance.startResolutionRetry(database,first.attempt._id,seller);assert.equal(retry.attempt.issuanceState,'put_succeeded_resolve_pending');const resolved=await issuance.markResolved(database,first.attempt._id,{invoiceNumber:456,invoiceGuid:'G-456',result:{Number:456}},seller);assert.equal(resolved.invoiceNumber,456);assert.equal(resolved.putCallCount,1);assert.equal(resolved.resolveAttemptCount,1);});

test('E: definitive pre-Put failure is the only state that permits a new safe attempt',async()=>{const database=db(),first=await prepared(database);const failed=await issuance.markConfirmedFailure(database,first.attempt._id,{error:'inventory validation rejected'},seller);assert.equal(failed.putCallCount,0);const next=await issuance.beginAttempt(database,{attemptId:'browser-b',body,mapping,user:seller});assert.equal(next.mayPut,true);assert.notEqual(next.attempt._id,first.attempt._id);});

test('F/G: double click and two browser sessions share one durable fingerprint owner',async()=>{const database=db(),first=await Promise.all([prepared(database,'double-a'),prepared(database,'double-a')]);assert.equal(first.filter(row=>row.mayPut).length,1);const winner=first.find(row=>row.mayPut);await issuance.markPutInProgress(database,winner.attempt._id,seller);const secondBrowser=await issuance.beginAttempt(database,{attemptId:'double-b',body,mapping,user:seller});assert.equal(secondBrowser.mayPut,false);assert.equal(secondBrowser.attempt.putCallCount,1);assert.equal(database.collection(issuance.ATTEMPTS).rows.length,1);});

test('resolved duplicate TTL blocks immediate replay but permits a fresh attempt after expiry',async()=>{const database=db(),at=new Date('2026-08-05T10:00:00Z');const first=await issuance.beginAttempt(database,{attemptId:'ttl-a',body,mapping,user:seller,at});await issuance.markPutInProgress(database,first.attempt._id,seller,at);await issuance.markPutSucceededResolvePending(database,first.attempt._id,{httpStatus:200},seller,at);await issuance.markResolved(database,first.attempt._id,{invoiceNumber:777,invoiceGuid:'G-777'},seller,at);const inside=await issuance.beginAttempt(database,{attemptId:'ttl-b',body,mapping,user:seller,at:new Date(at.getTime()+14*60*1000)});assert.equal(inside.mayPut,false);assert.equal(inside.attempt._id,first.attempt._id);const after=await issuance.beginAttempt(database,{attemptId:'ttl-c',body,mapping,user:seller,at:new Date(at.getTime()+16*60*1000)});assert.equal(after.mayPut,true);assert.notEqual(after.attempt._id,first.attempt._id);});

test('H/I/J: refresh, PM2 restart and host reboot use persisted server state',async()=>{const database=db(),first=await prepared(database);await issuance.markPutInProgress(database,first.attempt._id,seller);await issuance.markAmbiguous(database,first.attempt._id,{error:'restart'},seller);for(const simulatedProcess of [1,2,3]){const row=await database.collection(issuance.ATTEMPTS).findOne({_id:first.attempt._id});assert.equal(issuance.publicAttempt(row).state,'put_response_ambiguous',`process ${simulatedProcess}`);const replay=await issuance.beginAttempt(database,{attemptId:first.attempt._id,body,mapping,user:seller});assert.equal(replay.mayPut,false);}});

test('L/M/P: multiple/zero candidate outcomes require manual reconciliation and evidence',async()=>{for(const failureStage of ['multiple-candidates','candidate-search']){const database=db(),first=await prepared(database,`manual-${failureStage}`);await issuance.markPutInProgress(database,first.attempt._id,seller);await issuance.markPutSucceededResolvePending(database,first.attempt._id,{httpStatus:200,identifiers:{}},seller);const manual=await issuance.markManualReconciliation(database,first.attempt._id,{ok:false,code:'POST_PUT_RESOLVE_FAILED',failureStage,candidateCount:failureStage==='multiple-candidates'?2:0},seller);assert.equal(manual.issuanceState,'manual_reconciliation_required');await assert.rejects(issuance.confirmNoInvoice(database,first.attempt._id,{revision:manual.revision,reason:'reviewed',evidenceReference:'E-1'},seller),error=>error.code==='ISSUANCE_RECONCILIATION_FORBIDDEN');await assert.rejects(issuance.confirmNoInvoice(database,first.attempt._id,{revision:manual.revision,reason:'',evidenceReference:''},accounting),error=>error.code==='ISSUANCE_RECONCILIATION_EVIDENCE_REQUIRED');const confirmed=await issuance.confirmNoInvoice(database,first.attempt._id,{revision:manual.revision,reason:'Accounting checked official Shaygan reads',evidenceReference:'CASE-1'},accounting);assert.equal(confirmed.issuanceState,'confirmed_put_failure');assert.equal(confirmed.manualNoInvoiceEvidence.confirmedBy.username,'accounting-a');}});

test('request fingerprint is deterministic, business-complete and changes with invoice content',()=>{const a=issuance.requestFingerprint(body,mapping),b=issuance.requestFingerprint(structuredClone(body),structuredClone(mapping)),changed=issuance.requestFingerprint({...body,discountAmount:11},mapping);assert.equal(a,b);assert.match(a,/^[0-9a-f]{64}$/);assert.notEqual(a,changed);const material=issuance.fingerprintMaterial(body,mapping);assert.equal(material.items.length,2);assert.equal(material.extras[0].amount,5);assert.equal(material.customer.mobile,'09120000000');assert.equal(material.invoiceTotal,245);});

test('technical audit stores raw result only in invoiceAuditLogs while public status is bounded',async()=>{const database=db(),first=await prepared(database);await issuance.technicalAudit(database,{attemptId:first.attempt._id,stage:'invoice-put',state:'put_response_ambiguous',response:{status:0,raw:{secretTechnical:'raw'},error:'timeout'},user:seller});const audit=database.collection(issuance.AUDIT_LOGS).rows[0],publicRow=issuance.publicAttempt(first.attempt);assert.deepEqual(audit.technicalResult,{secretTechnical:'raw'});assert.equal(JSON.stringify(publicRow).includes('secretTechnical'),false);assert.equal(publicRow.actions.includes('refer_accounting'),false);});

test('manual reconciliation uses revision guard and cannot be silently overwritten',async()=>{const database=db(),first=await prepared(database);await issuance.markPutInProgress(database,first.attempt._id,seller);await issuance.markAmbiguous(database,first.attempt._id,{error:'lost'},seller);const retry=await issuance.startResolutionRetry(database,first.attempt._id,seller);const manual=await issuance.markManualReconciliation(database,first.attempt._id,{failureStage:'candidate-search'},seller);await assert.rejects(issuance.confirmNoInvoice(database,first.attempt._id,{revision:retry.attempt.revision,reason:'checked',evidenceReference:'CASE-2'},admin),error=>error.code==='ISSUANCE_REVISION_CONFLICT');const confirmed=await issuance.confirmNoInvoice(database,first.attempt._id,{revision:manual.revision,reason:'checked',evidenceReference:'CASE-2'},admin);assert.equal(confirmed.auditLog.at(-1).by.username,'admin-a');});
